<a href="https://colab.research.google.com/github/Cr1ss4nB/Curso-ONE-Alura-AgentesIA/blob/main/AulaPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Aula de Python**

# **Clase Número 1 - Introducción al Lenguaje**

In [ ]:
print("Hola Mundo" + ", aquí vamos!")

Hola Mundo, aquí vamos!

In [ ]:
print(3 * 5)

15

In [ ]:
producto_1 = "Chocolate"
producto_2 = "Helado"
producto_3 = "Celular"

print("Productos:")
print("Producto 1: " + producto_1)
print("Producto 2: " + producto_2)
print("Producto 3: " + producto_3)

Productos:
Producto 1: Chocolate
Producto 2: Helado
Producto 3: Celular

In [ ]:
total_compra = producto_1 + " " + producto_2 + " " + producto_3
print("Total de la Compra: " + total_compra)

Total de la Compra: Chocolate Helado Celular

In [ ]:
amigos = 6
alquiler = 900
supermercado = 500
vehiculo = 400

total = alquiler + supermercado + vehiculo
print("El valor total del viaje es ", total)

alquiler = 800
total = alquiler + supermercado + vehiculo
print("El valor total del viaje es ", total)

alquiler = alquiler - 100
print(alquiler)

total_vehiculos = vehiculo * 2
print("Valor de vehìculos: ", total_vehiculos)

total_final = alquiler + supermercado + total_vehiculos
print("Total Final: ", total_final)

total_por_persona = total_final / amigos
print("Total por persona: ", total_por_persona)

El valor total del viaje es  1800
El valor total del viaje es  1700
700
Valor de vehìculos:  800
Total Final:  2000
Total por persona:  333.3333333333333

In [ ]:
from IPython.core.profiledir import ProfileDir
print("Tipo de Dato de Alquiler: ", type(alquiler))
print("Tipo de Dato de Total por Persona: ", type(total_por_persona))
print("Tipo de Producto: ", type(producto_1))

tieneLicencia = True
tieneLicencia = False

print("Cristian tiene licencia para conducir: ", tieneLicencia)

print("Tipo de Dato de Tiene Licencia: ", type(tieneLicencia))

Tipo de Dato de Alquiler:  <class 'int'>
Tipo de Dato de Total por Persona:  <class 'float'>
Tipo de Producto:  <class 'str'>
Cristian tiene licencia para conducir:  False
Tipo de Dato de Tiene Licencia:  <class 'bool'>

In [ ]:
texto = "BIenVenIDo a ESTe CuRso dE AluRA"

print(texto)
print(texto.lower())
print(texto.upper())
print(texto.strip())
print(texto.title())

print("Texto sin los espacios intermedios:")
print(texto.replace(" ", " / "))

texto = texto.lower().strip().replace(" "," - ")
print(texto)

BIenVenIDo a ESTe CuRso dE AluRA
bienvenido a este curso de alura
BIENVENIDO A ESTE CURSO DE ALURA
BIenVenIDo a ESTe CuRso dE AluRA
Bienvenido A Este Curso De Alura
Texto sin los espacios intermedios:
BIenVenIDo / a / ESTe / CuRso / dE / AluRA
bienvenido - a - este - curso - de - alura

In [ ]:
nombre = input("Ingrese su nombre: ")
print("Nombre: ", nombre )

edad = int(input("Ingrese su edad: "))
print("Edad: ", edad)
print("Tipo: ", type(edad))
print("Tipo entero:", type(int(edad)))

print("El nombre es " + nombre + " y su edad es de "+ str(edad) + " años.")

print(f"El nombre es {nombre} y la edad es {edad}") # Habilita a poner variables dentro del texto pero toca poner las variables entre llaves {}

Ingrese su nombre: Cristian
Nombre:  Cristian
Ingrese su edad: 24
Edad:  24
Tipo:  <class 'int'>
Tipo entero: <class 'int'>
El nombre es Cristian y su edad es de 24 años.
El nombre es Cristian y la edad es 24

In [ ]:
nombre=input("Ingrese su nombre: ")
# edad=int(input("Ingrese su edad: "))


# if edad >=18:
#   print(f"{nombre} usted puede ingresar al establecimiento porque tiene {edad} años")
# else:
#   print(f"{nombre} usted no puede ingresar porque tiene {edad} años. Por lo tanto es menor de edad")

promedio = float(input("Ingrese su promedio "))

if promedio >= 4.5 and promedio < 5:
  print(f"{nombre} ha aprobado con {promedio} sobresaliente")
elif promedio >= 4 and promedio < 4.5:
  print(f"{nombre} ha aprobado {promedio} muy bien")
elif promedio >= 3 and promedio < 4:
  print(f"{nombre} aprobó {promedio} regular")
elif promedio >= 0 and promedio < 3:
  print(f"{nombre} reprobó {promedio} la asignatura")
else:
  print("Ingrese una nota valida entre 0 y 5")

Ingrese su nombre: Cristian
Ingrese su promedio 60
Ingrese una nota valida entre 0 y 5

In [ ]:
edad = 24

if edad >= 18:
    print("Puede entrar a la fiesta")
    print("¡Bienvenido!")
else:
    print("Acceso denegado")

Puede entrar a la fiesta
¡Bienvenido!

# **Clase Número 2 - Conectando Python con la IA**

In [ ]:
import os
from google.colab import userdata
os.environ["GEMINI_API_KEY"] = userdata.get("GEMINI_API_KEY")

In [ ]:
from google import genai

client = genai.Client()

In [ ]:
respuesta = client.models.generate_content(model="gemini-3.1-flash-lite", contents="Que es la IA")

In [ ]:
print(respuesta.text)

La **Inteligencia Artificial (IA)** es un campo de la informática que busca crear sistemas o máquinas capaces de realizar tareas que, normalmente, requerirían de la inteligencia humana.

En lugar de seguir una lista rígida de instrucciones (como un programa de computadora tradicional), los sistemas de IA están diseñados para **aprender de los datos, identificar patrones y tomar decisiones o predicciones.**

Aquí te explico los conceptos clave para entenderla mejor:

### 1. ¿Cómo funciona? (Aprendizaje Automático)
La mayoría de las IA modernas utilizan algo llamado **"Aprendizaje Automático" (Machine Learning)**. Imagina que quieres enseñarle a una computadora a reconocer un gato:
*   En lugar de programar cada regla (ej. "tiene orejas puntiagudas", "tiene bigotes"), le das miles de fotos de gatos.
*   La máquina analiza los píxeles y encuentra por sí sola los patrones comunes.
*   Con el tiempo, cuando le muestras una foto nueva, la IA "predice" con alta probabilidad si es un gato o no.

### 2. Tipos de IA
*   **IA Estrecha (o Débil):** Es la que usamos hoy. Está diseñada para una tarea específica: jugar ajedrez, traducir idiomas, recomendar películas en Netflix o generar textos (como ChatGPT). No tiene conciencia ni voluntad propia.
*   **IA General (AGI):** Es un concepto teórico. Se refiere a una máquina que tendría una inteligencia igual a la humana en todos los aspectos, capaz de aprender cualquier tarea intelectual. Aún no existe.

### 3. Ejemplos de IA en tu vida diaria
Seguramente ya interactúas con ella todos los días:
*   **Asistentes virtuales:** Siri, Alexa o el Asistente de Google.
*   **Recomendaciones:** Los videos que te sugiere YouTube o las canciones en Spotify.
*   **Navegación:** Google Maps calculando la mejor ruta basándose en el tráfico en tiempo real.
*   **IA Generativa:** Herramientas como ChatGPT (texto), Midjourney (imágenes) o herramientas de traducción automática.
*   **Filtros de Spam:** Tu correo electrónico identifica automáticamente qué es basura y qué no.

### 4. ¿Por qué es importante ahora?
Aunque el concepto existe desde los años 50, ha explotado en los últimos años debido a tres factores:
1.  **Big Data:** Ahora tenemos cantidades masivas de datos para entrenar a las máquinas.
2.  **Poder de cómputo:** Las computadoras son mucho más rápidas y potentes.
3.  **Algoritmos avanzados:** Se han descubierto formas mucho más eficientes de procesar información (como las redes neuronales profundas).

### En resumen:
La IA no es "mágica", es **matemática y estadística aplicada a gran escala**. No "piensa" como un ser humano, sino que procesa información a una velocidad y volumen que los humanos no podríamos alcanzar, permitiéndole realizar tareas complejas con una precisión asombrosa.

¿Te gustaría saber sobre alguna aplicación específica o cómo funciona algún modelo en particular?

In [ ]:
print("*********************")

*********************

In [ ]:
n = 1

while n <=15:
  print("*")
  n = n + 1
print("Ya salimos del while")

*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
Ya salimos del while

In [ ]:
chat = client.chats.create(model="gemini-3.1-flash-lite")

In [ ]:
respuesta = chat.send_message("Que es la IA")

In [ ]:
print(respuesta)

sdk_http_response=HttpResponse(
  headers=<dict len=11>
) candidates=[Candidate(
  content=Content(
    parts=[
      Part(
        text="""La **Inteligencia Artificial (IA)** es una rama de la informática que busca crear sistemas o máquinas capaces de realizar tareas que, normalmente, requieren de la inteligencia humana.

En lugar de seguir una lista rígida de instrucciones (como un programa de computadora tradicional), los sistemas de IA están diseñados para **aprender de los datos, identificar patrones y tomar decisiones o predicciones**.

Aquí te explico los puntos clave para entenderla mejor:

### 1. ¿Cómo funciona?
La mayoría de las IA modernas funcionan mediante algo llamado **Aprendizaje Automático** (*Machine Learning*). Imagina que quieres enseñarle a una computadora a reconocer un gato:
* **Programación tradicional:** Tendrías que describirle cada detalle (forma de las orejas, bigotes, tamaño).
* **IA:** Le das miles de fotos de gatos y la máquina analiza por sí sola los patrones comunes hasta que aprende a identificar qué es un gato sin que tú se lo hayas explicado explícitamente.

### 2. Tipos de IA
* **IA Estrecha (Débil):** Es la que usamos hoy en día. Está diseñada para una tarea específica: jugar ajedrez, traducir idiomas, recomendar películas en Netflix o manejar un coche autónomo. No "piensa" en un sentido amplio, solo es muy buena en su función.
* **IA General (Fuerte):** Es un concepto teórico. Se refiere a una máquina que tendría una inteligencia igual a la humana, capaz de aprender cualquier tarea intelectual, razonar, planear y resolver problemas en cualquier contexto. Aún no existe.

### 3. ¿Dónde está presente hoy?
Probablemente ya interactúas con ella todo el tiempo:
* **Asistentes virtuales:** Siri, Alexa o el Asistente de Google.
* **Recomendaciones:** Los algoritmos de YouTube, Spotify, TikTok o Amazon.
* **IA Generativa:** Herramientas como **ChatGPT** (que puede escribir textos o código) o **Midjourney** (que crea imágenes).
* **Medicina:** Ayuda a los médicos a detectar enfermedades en radiografías con mucha precisión.
* **Finanzas:** Detecta fraudes bancarios analizando patrones extraños en tus compras.

### 4. ¿Por qué es tan importante ahora?
Aunque el concepto existe desde los años 50, la IA ha explotado recientemente por tres razones:
1. **Big Data:** Tenemos cantidades masivas de datos disponibles en internet para que las máquinas aprendan.
2. **Poder de cómputo:** Las computadoras actuales son extremadamente rápidas y capaces de procesar información compleja.
3. **Algoritmos avanzados:** Se han desarrollado nuevas técnicas (como las redes neuronales profundas) que imitan el funcionamiento básico de las conexiones cerebrales.

### En resumen:
La IA no es "mágica", es **matemática avanzada y estadística aplicada a una escala enorme**. Su objetivo principal es actuar como una herramienta que nos ayude a procesar información, automatizar tareas repetitivas y resolver problemas complejos mucho más rápido de lo que lo haríamos los humanos.

¿Te gustaría saber sobre algún tipo de IA en específico o cómo se aplica en algún área en particular?""",
        thought_signature=b'\x124\n2\x01\x11M2\x0f\xae\xf3\x95\xe7-\xa0I\x1cE\xe8|\')\x1cq\x0f\x0cx\xe7\xba\xaa\x1eZG\xda\xbe\x9b"\xb4Z\x98\x02,\x14_\xbc\xc4\xe4iu\x8b\xe87\x14X'
      ),
    ],
    role='model'
  ),
  finish_reason=<FinishReason.STOP: 'STOP'>,
  index=0
)] create_time=None model_version='gemini-3.1-flash-lite' prompt_feedback=None response_id='l2hRas-XH4GPjrEPvryVuAk' usage_metadata=GenerateContentResponseUsageMetadata(
  candidates_token_count=679,
  prompt_token_count=5,
  prompt_tokens_details=[
    ModalityTokenCount(
      modality=<MediaModality.TEXT: 'TEXT'>,
      token_count=5
    ),
  ],
  total_token_count=684
) model_status=None automatic_function_calling_history=[] parsed=None

In [ ]:
respuesta =chat.send_message("Cuando se lanzo chatGPT")
print(respuesta.text)

ChatGPT fue lanzado oficialmente por la empresa **OpenAI** el **30 de noviembre de 2022**.

Aquí hay algunos datos interesantes sobre su lanzamiento:

*   **Versión inicial:** Se lanzó como una "vista previa de investigación" gratuita basada en el modelo **GPT-3.5**.
*   **Impacto inmediato:** Se convirtió en la aplicación de más rápido crecimiento en la historia hasta ese momento, alcanzando los **100 millones de usuarios activos mensuales en solo dos meses** (enero de 2023).
*   **Evolución:** Posteriormente, OpenAI lanzó versiones más potentes como **GPT-4** (marzo de 2023), que introdujo capacidades de razonamiento más complejo y mayor precisión.

Desde su lanzamiento, la herramienta marcó un antes y un después en la adopción masiva de la Inteligencia Artificial generativa por parte del público general.

In [ ]:
chat.get_history()

[UserContent(
   parts=[
     Part(
       text='Que es la IA'
     ),
   ],
   role='user'
 ),
 Content(
   parts=[
     Part(
       text="""La **Inteligencia Artificial (IA)** es una rama de la informática que busca crear sistemas o máquinas capaces de realizar tareas que, normalmente, requieren de la inteligencia humana.

 En lugar de seguir una lista rígida de instrucciones (como un programa de computadora tradicional), los sistemas de IA están diseñados para **aprender de los datos, identificar patrones y tomar decisiones o predicciones**.

 Aquí te explico los puntos clave para entenderla mejor:

 ### 1. ¿Cómo funciona?
 La mayoría de las IA modernas funcionan mediante algo llamado **Aprendizaje Automático** (*Machine Learning*). Imagina que quieres enseñarle a una computadora a reconocer un gato:
 * **Programación tradicional:** Tendrías que describirle cada detalle (forma de las orejas, bigotes, tamaño).
 * **IA:** Le das miles de fotos de gatos y la máquina analiza por sí sola los patrones comunes hasta que aprende a identificar qué es un gato sin que tú se lo hayas explicado explícitamente.

 ### 2. Tipos de IA
 * **IA Estrecha (Débil):** Es la que usamos hoy en día. Está diseñada para una tarea específica: jugar ajedrez, traducir idiomas, recomendar películas en Netflix o manejar un coche autónomo. No "piensa" en un sentido amplio, solo es muy buena en su función.
 * **IA General (Fuerte):** Es un concepto teórico. Se refiere a una máquina que tendría una inteligencia igual a la humana, capaz de aprender cualquier tarea intelectual, razonar, planear y resolver problemas en cualquier contexto. Aún no existe.

 ### 3. ¿Dónde está presente hoy?
 Probablemente ya interactúas con ella todo el tiempo:
 * **Asistentes virtuales:** Siri, Alexa o el Asistente de Google.
 * **Recomendaciones:** Los algoritmos de YouTube, Spotify, TikTok o Amazon.
 * **IA Generativa:** Herramientas como **ChatGPT** (que puede escribir textos o código) o **Midjourney** (que crea imágenes).
 * **Medicina:** Ayuda a los médicos a detectar enfermedades en radiografías con mucha precisión.
 * **Finanzas:** Detecta fraudes bancarios analizando patrones extraños en tus compras.

 ### 4. ¿Por qué es tan importante ahora?
 Aunque el concepto existe desde los años 50, la IA ha explotado recientemente por tres razones:
 1. **Big Data:** Tenemos cantidades masivas de datos disponibles en internet para que las máquinas aprendan.
 2. **Poder de cómputo:** Las computadoras actuales son extremadamente rápidas y capaces de procesar información compleja.
 3. **Algoritmos avanzados:** Se han desarrollado nuevas técnicas (como las redes neuronales profundas) que imitan el funcionamiento básico de las conexiones cerebrales.

 ### En resumen:
 La IA no es "mágica", es **matemática avanzada y estadística aplicada a una escala enorme**. Su objetivo principal es actuar como una herramienta que nos ayude a procesar información, automatizar tareas repetitivas y resolver problemas complejos mucho más rápido de lo que lo haríamos los humanos.

 ¿Te gustaría saber sobre algún tipo de IA en específico o cómo se aplica en algún área en particular?""",
       thought_signature=b'\x124\n2\x01\x11M2\x0f\xae\xf3\x95\xe7-\xa0I\x1cE\xe8|\')\x1cq\x0f\x0cx\xe7\xba\xaa\x1eZG\xda\xbe\x9b"\xb4Z\x98\x02,\x14_\xbc\xc4\xe4iu\x8b\xe87\x14X'
     ),
   ],
   role='model'
 ),
 UserContent(
   parts=[
     Part(
       text='Cuando se lanzo chatGPT'
     ),
   ],
   role='user'
 ),
 Content(
   parts=[
     Part(
       text="""ChatGPT fue lanzado oficialmente por la empresa **OpenAI** el **30 de noviembre de 2022**.

 Aquí hay algunos datos interesantes sobre su lanzamiento:

 *   **Versión inicial:** Se lanzó como una "vista previa de investigación" gratuita basada en el modelo **GPT-3.5**.
 *   **Impacto inmediato:** Se convirtió en la aplicación de más rápido crecimiento en la historia hasta ese momento, alcanzando los **100 millones de usuarios activos mensuales en solo dos meses** (enero de 2023).
 *   **Evolución:** Posteriormente, OpenAI lanzó versiones más potentes como **GPT-4** (marzo de 2023), que introdujo capacidades de razonamiento más complejo y mayor precisión.

 Desde su lanzamiento, la herramienta marcó un antes y un después en la adopción masiva de la Inteligencia Artificial generativa por parte del público general.""",
       thought_signature=b'\x124\n2\x01\x11M2\x0f\xfa_\xdaAhk\xdb\xf58*\xca {\xf1`\x1d\xb8\xad\xb3\xa7\xf9\x8b\xf3~\x95pIwQU\x9f\x1a\x11\xe6)"\xd8\xdf\x9e[\x96\xbdh[\xf7'
     ),
   ],
   role='model'
 )]

In [ ]:
prompt = input("Ingrese su pregunta: ")

while prompt != "fin":
  respuesta=chat.send_message(prompt)
  print(respuesta.text)
  prompt = input("Ingrese su pregunta (fin para terminar): ")

Ingrese su pregunta: Qué ejercicios para bicep pueden reemplazar el curl predicador?
El **curl predicador** es excelente porque bloquea el movimiento del hombro (al estar apoyado), lo que obliga al bíceps a trabajar de forma aislada sin usar impulso.

Para reemplazarlo, necesitas ejercicios que compartan esa característica de **aislamiento** o que enfoquen el esfuerzo en la **fase de estiramiento** del bíceps. Aquí tienes las mejores alternativas según tu equipo:

### 1. Curl con barra o mancuerna sentado con apoyo (Spider Curl)
Si quieres el "hermano gemelo" del predicador, este es el mejor.
*   **Cómo hacerlo:** Acuéstate boca abajo (o inclinado unos 45 grados) sobre un banco inclinado. Deja que tus brazos cuelguen hacia el suelo y realiza el curl desde esa posición.
*   **Por qué funciona:** Al igual que en el predicador, el apoyo del banco impide que balancees el cuerpo, pero aquí el bíceps comienza en una posición de estiramiento total, lo que genera un estímulo muy potente para la hipertrofia.

### 2. Curl en banco inclinado (Incline Dumbbell Curl)
Este es probablemente el mejor ejercicio para darle "pico" al bíceps porque enfatiza la cabeza larga del músculo.
*   **Cómo hacerlo:** Siéntate en un banco con una inclinación de unos 45-60 grados. Deja caer los brazos totalmente hacia atrás y realiza el curl.
*   **Por qué funciona:** Al tener los hombros hacia atrás, el bíceps queda en una posición de estiramiento extremo. El rango de movimiento es mayor y es imposible hacer "trampa" si mantienes los codos fijos.

### 3. Curl de concentración (Concentration Curl)
Este es el ejercicio clásico de aislamiento total.
*   **Cómo hacerlo:** Sentado en un banco, apoya el tríceps (la parte superior del brazo) en la cara interna de tu muslo. Realiza el curl sin despegar el codo de la pierna.
*   **Por qué funciona:** Elimina por completo cualquier posibilidad de involucrar la espalda o el hombro. Es ideal para el trabajo de conexión mente-músculo y para terminar la rutina con un "pump" máximo.

### 4. Curl en polea baja con apoyo de espalda
Si tienes acceso a poleas, esta es una variante muy efectiva.
*   **Cómo hacerlo:** Coloca un banco vertical frente a la polea baja. Siéntate y pega bien la espalda al respaldo. Realiza el curl con una barra recta o cuerda.
*   **Por qué funciona:** La polea mantiene una **tensión constante** durante todo el recorrido, a diferencia de las mancuernas donde hay puntos muertos. Al estar apoyado en el banco, eliminas el impulso, replicando la estabilidad del predicador.

### 5. Curl en máquina de bíceps (si tu gimnasio tiene)
Si tu gimnasio tiene la máquina específica de curl de bíceps (donde te sientas y apoyas los brazos), es el reemplazo técnico más directo.
*   **Tip:** Si la máquina es muy vertical, intenta inclinarte un poco hacia adelante para que el ángulo de trabajo sea similar al del banco predicador tradicional.

---

### ¿Cuál elegir según tu objetivo?

*   **Si buscas el mayor estiramiento:** Ve por el **Curl en banco inclinado**.
*   **Si buscas máxima estabilidad/aislamiento:** Ve por el **Spider Curl** o el **Curl de concentración**.
*   **Si buscas tensión constante:** Usa la **polea baja con apoyo**.

**Un consejo extra:** Si el motivo por el que quieres cambiar el predicador es porque sientes dolor en las muñecas o los codos (algo común en ese ejercicio), prueba a usar **mancuernas con agarre neutro (tipo martillo)** o una **barra EZ** en lugar de una barra recta, ya que la posición de la muñeca es más natural y menos lesiva.
Ingrese su pregunta (fin para terminar): fin

In [ ]:
nombres = ["Juan","Laura","Fernando","Andrés","Cristian"]
# pos.       0       1         2          3        4
print(nombres)

['Juan', 'Laura', 'Fernando', 'Andrés', 'Cristian']

In [ ]:
print("El quinto elemento es:",nombres[4])

El quinto elemento es: Cristian

In [ ]:
promedios = [8.5, 6.5, 7.3, 9.5, 6.3, 2.5, 4.8]
print(promedios[3])

9.5

In [ ]:
n=0 #1

while n < len(promedios):
  promedios[n]=promedios[n]+1
  if promedios[n]>10:
     promedios[n]=10
  n=n+1
print("Los promedios mejorados son:",promedios)

Los promedios mejorados son: [9.5, 7.5, 8.3, 10, 7.3, 3.5, 5.8]

In [ ]:
print("Cantidad de elementos en la lista:",len(promedios))

Cantidad de elementos en la lista: 7

In [ ]:
print(promedios[-1])
print(promedios[-2])
print(promedios[-3])

5.8
3.5
7.3

# Funcionamiento de la Indexación Negativa

Cuando se usa un índice negativo, Python comienza a contar desde el final. Así, el índice -1 corresponde al último elemento, -2 al penúltimo, y así sucesivamente. Este conteo inverso es útil para acceder a elementos sin necesidad de saber el tamaño exacto de la lista. Por ejemplo:

In [ ]:
nombres = ['María', 'Juan', 'Ana', 'Pedro', 'Juliana']

print(nombres[-1])  # Muestra 'Juliana'
print(nombres[-2])  # Muestra 'Pedro'


# Ejemplo de slicing con índice negativo
ultimos_tres = nombres[-3:]
print(ultimos_tres)  # Muestra ['Ana', 'Pedro', 'Juliana']

Juliana
Pedro
['Ana', 'Pedro', 'Juliana']

### Continuando...

In [ ]:
nombres=["Cristian Basto","Juan Cely","Luis Briseño","Laura Supernova","Camila Rojas"]
print(nombres)

nombres[1:3]

['Cristian Basto', 'Juan Cely', 'Luis Briseño', 'Laura Supernova', 'Camila Rojas']

['Juan Cely', 'Luis Briseño']

In [ ]:
nombres.append("Rodrigo Kumis")
print(nombres)

['Cristian Basto', 'Juan Cely', 'Luis Briseño', 'Laura Supernova', 'Camila Rojas', 'Rodrigo Kumis']

In [ ]:
print("Cantidad de elementos:",len(nombres))

Cantidad de elementos: 6

In [ ]:
nombres.extend(["Nicolas Gamboa","Nancy Zapata"])
print(nombres)

['Cristian Basto', 'Juan Cely', 'Luis Briseño', 'Laura Supernova', 'Camila Rojas', 'Rodrigo Kumis', 'Nicolas Gamboa', 'Nancy Zapata']

In [ ]:
nombres.append(["Pepe Primero 0","Pepo Último 1"])

In [ ]:
print(nombres)

['Cristian Basto', 'Juan Cely', 'Luis Briseño', 'Laura Supernova', 'Camila Rojas', 'Rodrigo Kumis', 'Nicolas Gamboa', 'Nancy Zapata', ['Pepe Primero 0', 'Pepo Último 1']]

In [ ]:
nombres[8][1]

'Pepo Último 1'

In [ ]:
nombres[-1][-2]

'Pepe Primero 0'

In [ ]:
nombres.remove("Nicolas Gamboa")

In [ ]:
nombres

['Cristian Basto',
 'Juan Cely',
 'Luis Briseño',
 'Laura Supernova',
 'Camila Rojas',
 'Rodrigo Kumis',
 'Nancy Zapata',
 ['Pepe Primero 0', 'Pepo Último 1']]

In [ ]:
nombres.pop()
nombres

['Cristian Basto',
 'Juan Cely',
 'Luis Briseño',
 'Laura Supernova',
 'Camila Rojas',
 'Rodrigo Kumis',
 'Nancy Zapata']

In [ ]:
nombres.pop(4)
nombres

['Cristian Basto',
 'Juan Cely',
 'Luis Briseño',
 'Laura Supernova',
 'Rodrigo Kumis',
 'Nancy Zapata']

Diccionarios:

estudiantes=["clave":valor]

In [ ]:
nombres=["Cristian Basto","Juan Cely","Luis Briseño","Laura Supernova","Camila Rojas"]
promedios = [8.5,6.5,7.3,9.5,6.3,2.5,4.8]

estudiantes = {
    "Cristian Basto":8.5,
    "Juan Cely":6.5,
    "Luis Briseño":7.3,
    "Laura Supernova":6.3,
    "Camila Rojas":2.5
}

print(nombres)
print(promedios)
print(estudiantes)

['Cristian Basto', 'Juan Cely', 'Luis Briseño', 'Laura Supernova', 'Camila Rojas']
[8.5, 6.5, 7.3, 9.5, 6.3, 2.5, 4.8]
{'Cristian Basto': 8.5, 'Juan Cely': 6.5, 'Luis Briseño': 7.3, 'Laura Supernova': 6.3, 'Camila Rojas': 2.5}

In [ ]:
print(estudiantes["Cristian Basto"])
print(estudiantes.get("Cristian Basto"))

8.5
8.5

In [ ]:
print(estudiantes.items())

dict_items([('Cristian Basto', 8.5), ('Juan Cely', 6.5), ('Luis Briseño', 7.3), ('Laura Supernova', 6.3), ('Camila Rojas', 2.5)])

In [ ]:
estudiantes.pop("Laura Supernova")
estudiantes

{'Cristian Basto': 8.5,
 'Juan Cely': 6.5,
 'Luis Briseño': 7.3,
 'Camila Rojas': 2.5}

In [ ]:
print(estudiantes.keys())

dict_keys(['Cristian Basto', 'Juan Cely', 'Luis Briseño', 'Camila Rojas'])

In [ ]:
print(estudiantes.values())

NameError: name 'estudiantes' is not defined

In [ ]:
persona= {
    "nombre":"Juan Perez",
    "edad":25,
    "materias":["Matematica","Literatura","Dibujo"]
}

print(persona)

{'nombre': 'Juan Perez', 'edad': 25, 'materias': ['Matematica', 'Literatura', 'Dibujo']}

In [ ]:
estudiante1 = {
    "nombre":"Juan Perez","edad":25
    }

estudiante2 = {
    "nombre":"Laura Fernandez","edad":28
    }

print(estudiante1)
print(estudiante2)

{'nombre': 'Juan Perez', 'edad': 25}
{'nombre': 'Laura Fernandez', 'edad': 28}

In [ ]:
lista_de_estudiantes= [
    {
    "nombre":"Juan Perez","edad":25
    },
    {
    "nombre":"Laura Fernandez","edad":28
    }
]

print(lista_de_estudiantes)

[{'nombre': 'Juan Perez', 'edad': 25}, {'nombre': 'Laura Fernandez', 'edad': 28}]

In [ ]:
lista_de_estudiantes[1]

{'nombre': 'Laura Fernandez', 'edad': 28}

In [ ]:
lista_de_estudiantes[1]["edad"]

NameError: name 'lista_de_estudiantes' is not defined

# Clase Número 3 - Entrada y conversión de Datos

In [ ]:
lista_de_estudiantes= [
    {
    "nombre":"Juan Perez","edad":25
    },
    {
    "nombre":"Laura Fernandez","edad":28
    }
]

n =0

while n < len(lista_de_estudiantes):
  print(lista_de_estudiantes[n])
  n+=1

for elemento in lista_de_estudiantes:
  print(elemento)

print("con cantidad definida")
for n in range(5):
  print(n)
print("con rango definido")

for n in range(2,8):
  print(n)
print("con internvalos")
for n in range(2,8,2):
  print(n)

{'nombre': 'Juan Perez', 'edad': 25}
{'nombre': 'Laura Fernandez', 'edad': 28}
{'nombre': 'Juan Perez', 'edad': 25}
{'nombre': 'Laura Fernandez', 'edad': 28}
con cantidad definida
0
1
2
3
4
con rango definido
2
3
4
5
6
7
con internvalos
2
4
6

In [ ]:
persona= {
    "nombre":"Juan Perez",
    "edad":25,
    "materias":["Matematica","Literatura","Dibujo"]
}

for clave,valor in persona.items():
  print(f"La clave es: {clave} y el valor es: {valor}")

for n in range(11):
  if n % 2  == 0:
    print(n)

La clave es: nombre y el valor es: Juan Perez
La clave es: edad y el valor es: 25
La clave es: materias y el valor es: ['Matematica', 'Literatura', 'Dibujo']
0
2
4
6
8
10

In [ ]:


nombres_1 = "   jUAn  pErez  "
nombres_2 = "mArIA   gONzaLeZ    "
nombres_3 = "   rOdRiGo   saNchEz "
nombres_4 = "  ELisAbEtH   fLoREs"

In [ ]:
def corregir_texto(texto):
  print(" ".join(texto.title().split()))

In [ ]:
corregir_texto(" LauRA fernandez  ")

Laura Fernandez

In [ ]:
corregir_texto(nombres_1)
corregir_texto(nombres_2)
corregir_texto(nombres_3)
corregir_texto(nombres_4)

Juan Perez
Maria Gonzalez
Rodrigo Sanchez
Elisabeth Flores

In [ ]:
nombres_1.split()

['jUAn', 'pErez']

In [ ]:
texto_corregido= " ".join(nombres_1.split())
print(texto_corregido)

jUAn pErez

In [ ]:
salones = ["Salón 1", "Salón 2","Salón 3"]

In [ ]:
import random

def ubica_alumnos(nombre_alumno,lista_salones):
  salon_asignado=random.choice(lista_salones)

  dict_alumnos= {
      "nombre":nombre_alumno,
      "salon":salon_asignado
  }
  print(dict_alumnos)

In [ ]:
def corrije_texto(texto):
  texto_nuevo=texto.upper()
  lista_palabras=texto_nuevo.split()
  nombre_final= " ".join(lista_palabras)
  return nombre_final

In [ ]:
nombre_optimizado=corrije_texto(nombres_2)

ubica_alumnos(nombre_optimizado,salones)

{'nombre': 'MARIA GONZALEZ', 'salon': 'Salón 2'}

In [ ]:
ubica_alumnos("Roberto Gonzalez",salones)

{'nombre': 'Roberto Gonzalez', 'salon': 'Salón 2'}

Desafio:

1. Pedirle a una IA que nos genere 20 emails aleatorios en strings
2. Crear una función que va a recibir como argumento la lista de emails y le va a pedir a una IA que los resuma en una sola linea

In [ ]:
cuerpos_emails = [
    "Hola, te envío los archivos adjuntos con el reporte mensual de ventas. Quedo atento a tus comentarios.",
    "Estimado equipo, les recuerdo que la reunión quincenal se reprogramó para mañana a las 10:00 AM.",
    "Tu contraseña expirará en 3 días. Por seguridad, ingresa a tu perfil para actualizarla.",
    "¡Solo por hoy! Disfruta de un 30% de descuento en toda nuestra tienda usando el cupón VERANO30.",
    "Feliz cumpleaños. Espero que pases un día excelente rodeado de tu familia y amigos. ¡Un abrazo!"
]

In [ ]:
def resumir_emails(cuerpos_emails):
  for numero, email in enumerate(cuerpos_emails):
    respuesta = client.models.generate_content(
        model="gemini-3.1-flash-lite",
        contents=f"""Te voy a enviar el cuerpo de un correo electronico y necesito que lo resumas en una sola linea. Dejando clara la intención de dicho correo. La respuesta debe ser una unica linea. El correo es el siguiente:{email}""")
    print(f"E-Mail N° {numero + 1}: {respuesta.text}")

In [ ]:
resumir_emails(cuerpos_emails)

E-Mail N° 1: Envío del reporte mensual de ventas para tu revisión y comentarios.
E-Mail N° 2: Recordatorio: La reunión quincenal ha sido reprogramada para mañana a las 10:00 AM.
E-Mail N° 3: Debes actualizar tu contraseña en el perfil antes de 3 días por motivos de seguridad.
E-Mail N° 4: La tienda ofrece un 30% de descuento en todos sus productos solo por hoy utilizando el cupón VERANO30.
E-Mail N° 5: El correo tiene como intención felicitar al destinatario por su cumpleaños y expresarle buenos deseos.

In [ ]:
!pip install -q groq

In [ ]:
os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")

In [ ]:
from groq import Groq

client = Groq()
completion = client.chat.completions.create(
    model="openai/gpt-oss-120b",
    messages=[
      {
        "role": "user",
        "content": "que puedo comer hoy, dame una respuesta corta"
      }
    ],
    temperature=0.1, # define qué tan creativa será la respuesta. La respuesta más probable.
    max_completion_tokens=200,
    top_p=1,
    stream=True,
    stop=None
)

for chunk in completion:
    print(chunk.choices[0].delta.content or "", end="")

Una ensalada de quinoa con verduras, aguacate y pollo a la plancha, o un wrap de hummus, espinacas y pavo. ¡Listo en menos de 30 min!

# Clase Número 4 - Lectura y Escritura

### Lectura y escritura de archivos con Python
---

In [ ]:
def resumir_emails(cuerpos_emails):
  lista_resumenes = []
  for numero, email in enumerate(cuerpos_emails):
    respuesta = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": f"""Te voy a enviar el cuerpo de un correo electrónico. Quiero que lo resumas en una sola línea indicando la intención
                de dicho correo. El correo es el siguiente: {email}"""
            }
        ])
    texto = respuesta.choices[0].message.content
    print(f"E-Mail N° {numero + 1}: {texto}")
    lista_resumenes.append(f"E-Mail N° {numero + 1}: {texto}")
  return lista_resumenes

In [ ]:
resumir_emails(cuerpos_emails)

E-Mail N° 1: El remitente envía el reporte mensual de ventas y solicita comentarios sobre el mismo.
E-Mail N° 2: El correo electrónico es para recordar al equipo que la reunión quincenal ha sido reprogramada para el día siguiente a las 10:00 AM.
E-Mail N° 3: La intención del correo electrónico es notificar al destinatario que su contraseña caducará en 3 días y solicitarle que la actualice por motivos de seguridad.
E-Mail N° 4: El correo electrónico informa sobre una oferta limitada de un 30% de descuento en toda la tienda utilizando un cupón específico.
E-Mail N° 5: El correo electrónico es para desealar un feliz cumpleaños y enviar buenos deseos al destinatario.

['E-Mail N° 1: El remitente envía el reporte mensual de ventas y solicita comentarios sobre el mismo.',
 'E-Mail N° 2: El correo electrónico es para recordar al equipo que la reunión quincenal ha sido reprogramada para el día siguiente a las 10:00 AM.',
 'E-Mail N° 3: La intención del correo electrónico es notificar al destinatario que su contraseña caducará en 3 días y solicitarle que la actualice por motivos de seguridad.',
 'E-Mail N° 4: El correo electrónico informa sobre una oferta limitada de un 30% de descuento en toda la tienda utilizando un cupón específico.',
 'E-Mail N° 5: El correo electrónico es para desealar un feliz cumpleaños y enviar buenos deseos al destinatario.']

In [ ]:
lista_resumen = resumir_emails(cuerpos_emails)

E-Mail N° 1: El correo electrónico envía un reporte mensual de ventas y solicita comentarios o retroalimentación sobre el mismo.
E-Mail N° 2: El correo electrónico es un recordatorio sobre el cambio de fecha y hora de la reunión quincenal del equipo, que se llevará a cabo mañana a las 10:00 AM.
E-Mail N° 3: La intención del correo electrónico es notificar al usuario que su contraseña caducará en 3 días y solicitarle que la actualice por motivos de seguridad.
E-Mail N° 4: La intención del correo electrónico es ofrecer un descuento del 30% en la tienda durante un día, mediante el uso de un cupón promocional específico.
E-Mail N° 5: El destinatario del correo recibe un saludo de cumpleaños y una expresión de buenos deseos para su celebración.

In [ ]:
lista_resumen

['E-Mail N° 1: El correo electrónico envía un reporte mensual de ventas y solicita comentarios o retroalimentación sobre el mismo.',
 'E-Mail N° 2: El correo electrónico es un recordatorio sobre el cambio de fecha y hora de la reunión quincenal del equipo, que se llevará a cabo mañana a las 10:00 AM.',
 'E-Mail N° 3: La intención del correo electrónico es notificar al usuario que su contraseña caducará en 3 días y solicitarle que la actualice por motivos de seguridad.',
 'E-Mail N° 4: La intención del correo electrónico es ofrecer un descuento del 30% en la tienda durante un día, mediante el uso de un cupón promocional específico.',
 'E-Mail N° 5: El destinatario del correo recibe un saludo de cumpleaños y una expresión de buenos deseos para su celebración.']

In [ ]:
with open("lista-de-resumenes.txt", "w", encoding="utf-8") as archivo:
    for resumen in lista_resumen:
        archivo.write(resumen + "\n")

In [ ]:
lista_lectura = []

with open("lista-de-resumenes.txt", "r", encoding="utf-8") as archivo:
    for linea in archivo:
        lista_lectura.append(linea.strip())

In [ ]:
lista_lectura

['E-Mail N° 1: El correo electrónico envía un reporte mensual de ventas y solicita comentarios o retroalimentación sobre el mismo.',
 'E-Mail N° 2: El correo electrónico es un recordatorio sobre el cambio de fecha y hora de la reunión quincenal del equipo, que se llevará a cabo mañana a las 10:00 AM.',
 'E-Mail N° 3: La intención del correo electrónico es notificar al usuario que su contraseña caducará en 3 días y solicitarle que la actualice por motivos de seguridad.',
 'E-Mail N° 4: La intención del correo electrónico es ofrecer un descuento del 30% en la tienda durante un día, mediante el uso de un cupón promocional específico.',
 'E-Mail N° 5: El destinatario del correo recibe un saludo de cumpleaños y una expresión de buenos deseos para su celebración.']

In [ ]:
contenido = ""

with open("lista-de-resumenes.txt", "r", encoding="utf-8") as archivo:
    contenido = archivo.read()

In [ ]:
contenido

'E-Mail N° 1: El correo electrónico envía un reporte mensual de ventas y solicita comentarios o retroalimentación sobre el mismo.\nE-Mail N° 2: El correo electrónico es un recordatorio sobre el cambio de fecha y hora de la reunión quincenal del equipo, que se llevará a cabo mañana a las 10:00 AM.\nE-Mail N° 3: La intención del correo electrónico es notificar al usuario que su contraseña caducará en 3 días y solicitarle que la actualice por motivos de seguridad.\nE-Mail N° 4: La intención del correo electrónico es ofrecer un descuento del 30% en la tienda durante un día, mediante el uso de un cupón promocional específico.\nE-Mail N° 5: El destinatario del correo recibe un saludo de cumpleaños y una expresión de buenos deseos para su celebración.\n'

In [ ]:
nueva_lista = []

with open("lista-de-resumenes.txt", "r", encoding="utf-8") as archivo:
    nueva_lista = archivo.readlines()

In [ ]:
nueva_lista

['E-Mail N° 1: El correo electrónico envía un reporte mensual de ventas y solicita comentarios o retroalimentación sobre el mismo.\n',
 'E-Mail N° 2: El correo electrónico es un recordatorio sobre el cambio de fecha y hora de la reunión quincenal del equipo, que se llevará a cabo mañana a las 10:00 AM.\n',
 'E-Mail N° 3: La intención del correo electrónico es notificar al usuario que su contraseña caducará en 3 días y solicitarle que la actualice por motivos de seguridad.\n',
 'E-Mail N° 4: La intención del correo electrónico es ofrecer un descuento del 30% en la tienda durante un día, mediante el uso de un cupón promocional específico.\n',
 'E-Mail N° 5: El destinatario del correo recibe un saludo de cumpleaños y una expresión de buenos deseos para su celebración.\n']

In [ ]:
lista_lectura = []

with open("lista-de-resumenes.txt", "r", encoding="utf-8") as archivo:
    for linea in archivo:
        lista_lectura.append(linea.strip())

In [ ]:
lista_lectura

['E-Mail N° 1: El correo electrónico envía un reporte mensual de ventas y solicita comentarios o retroalimentación sobre el mismo.',
 'E-Mail N° 2: El correo electrónico es un recordatorio sobre el cambio de fecha y hora de la reunión quincenal del equipo, que se llevará a cabo mañana a las 10:00 AM.',
 'E-Mail N° 3: La intención del correo electrónico es notificar al usuario que su contraseña caducará en 3 días y solicitarle que la actualice por motivos de seguridad.',
 'E-Mail N° 4: La intención del correo electrónico es ofrecer un descuento del 30% en la tienda durante un día, mediante el uso de un cupón promocional específico.',
 'E-Mail N° 5: El destinatario del correo recibe un saludo de cumpleaños y una expresión de buenos deseos para su celebración.']

## **Manipulando dados com Pandas**

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/nombres_y_promedios.csv")

In [ ]:
df.head(2)

            Nombre  Promedio
0       Juan Pérez       2.1
1  María Rodríguez       4.5

In [ ]:
df.tail(3)

           Nombre  Promedio
7    Sofía Castro       1.8
8    Andrés Villa       3.9
9  Elena Espinoza       1.5

Desafio:
1. Criar um arquivo .txt a partir de uma lista de perguntas vindas de uma lista em Python [].
2. Ler as perguntas desse arquivo .txt e salvá-las em uma lista Python
3. Obter respostas de um LLM para cada uma.
4. Salvar os resultados em um novo arquivo .csv
5. Ler o arquivo .csv usando Pandas

In [ ]:
# Etapa 1
lista_de_preguntas = [
    "¿Cuál es la capital oficial de Australia?",
    "¿Qué instrumento se utiliza para medir la presión atmosférica?",
    "¿Cuántos huesos tiene el cuerpo humano de un adulto?",
    "¿En qué año comenzó la Primera Guerra Mundial?",
    "¿Cuál es el océano más grande y profundo de la Tierra?"
]

In [ ]:
with open("preguntas.txt", "w", encoding="utf-8") as archivo:
    for pregunta in lista_de_preguntas:
        archivo.write(pregunta + "\n")

In [ ]:
# Etapa 2
lista_desafio = []

with open("preguntas.txt", "r", encoding="utf-8") as archivo:
    for linea in archivo:
        lista_desafio.append(linea.strip())

print(lista_desafio)

['¿Cuál es la capital oficial de Australia?', '¿Qué instrumento se utiliza para medir la presión atmosférica?', '¿Cuántos huesos tiene el cuerpo humano de un adulto?', '¿En qué año comenzó la Primera Guerra Mundial?', '¿Cuál es el océano más grande y profundo de la Tierra?']

In [ ]:
# Etapa 3
lista_de_diccionarios_de_respuestas = []

for pregunta in lista_desafio:
    respuesta = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": f"""Te voy a enviar una pregunta y tú respondes con una respuesta corta. Pregunta: {pregunta}"""
            }
        ]
    )

    texto = respuesta.choices[0].message.content
    lista_de_diccionarios_de_respuestas.append({"pregunta":pregunta, "respuesta":texto})

In [ ]:
lista_de_diccionarios_de_respuestas

[{'pregunta': '¿Cuál es la capital oficial de Australia?',
  'respuesta': 'La capital oficial de Australia es Canberra.'},
 {'pregunta': '¿Qué instrumento se utiliza para medir la presión atmosférica?',
  'respuesta': 'El instrumento utilizado para medir la presión atmosférica es el barómetro.'},
 {'pregunta': '¿Cuántos huesos tiene el cuerpo humano de un adulto?',
  'respuesta': 'El cuerpo humano de un adulto tiene 206 huesos.'},
 {'pregunta': '¿En qué año comenzó la Primera Guerra Mundial?',
  'respuesta': 'La Primera Guerra Mundial comenzó en 1914.'},
 {'pregunta': '¿Cuál es el océano más grande y profundo de la Tierra?',
  'respuesta': 'El océano Pacífico es el más grande y profundo de la Tierra.'}]

In [ ]:
# Etapa 4
with open("respuestas1.csv", "w", encoding="utf-8") as archivo:
    archivo.write("pregunta,respuesta\n")
    for diccionario in lista_de_diccionarios_de_respuestas:
        archivo.write(f"{diccionario['pregunta']},{diccionario['respuesta']}\n")

In [ ]:
# Etapa 5

df = pd.DataFrame(lista_de_diccionarios_de_respuestas)
df.to_csv("respuestas1.csv", index=False, encoding="utf-8")

In [ ]:
df

,pregunta,respuesta
0,¿Cuál es la capital oficial de Australia?,La capital oficial de Australia es Canberra.
1,¿Qué instrumento se utiliza para medir la pres...,El instrumento utilizado para medir la presión...
2,¿Cuántos huesos tiene el cuerpo humano de un a...,El cuerpo humano de un adulto tiene 206 huesos.
3,¿En qué año comenzó la Primera Guerra Mundial?,La Primera Guerra Mundial comenzó en 1914.
4,¿Cuál es el océano más grande y profundo de la...,El océano Pacífico es el más grande y profundo...

# Clase Número 5 - Conociendo Pandas

In [ ]:
import pandas as pd
import random

# Definir posibles valores para las columnas
nombres_productos_posibles = [
    'Laptop', 'Smartphone', 'Tablet', 'Smartwatch', 'Auriculares', 'Teclado', 'Mouse', 'Monitor', 'Impresora', 'Altavoz',
    'Cámara', 'Disco Duro', 'Router', 'Webcam', 'Micrófono', 'Gafas VR', 'Consola', 'Control Remoto', 'Proyector', 'Batería Externa'
]
categorias_posibles = ['Electrónica', 'Hogar', 'Oficina', 'Entretenimiento', 'Accesorios']

# Seleccionar 10 nombres de productos únicos aleatoriamente
productos_elegidos = random.sample(nombres_productos_posibles, 10)

# Generar datos para las 10 filas
data = {
    'Nombre de producto': productos_elegidos,
    'Categoria': [random.choice(categorias_posibles) for _ in range(10)],
    'Precio': [round(random.uniform(50, 1500), 2) for _ in range(10)],
    'Stock': [random.randint(10, 100) for _ in range(10)]
}

# Crear el DataFrame
df_productos = pd.DataFrame(data)

# Mostrar el DataFrame
display(df_productos)

  Nombre de producto        Categoria   Precio  Stock
0             Tablet       Accesorios   190.11     23
1            Teclado            Hogar  1444.15     93
2              Mouse       Accesorios   542.15     20
3             Cámara      Electrónica   259.38     10
4             Router      Electrónica  1218.32     77
5        Auriculares          Oficina   550.09     53
6            Monitor      Electrónica  1101.57     95
7         Smartwatch       Accesorios  1193.70     57
8             Webcam          Oficina  1302.93     47
9            Altavoz  Entretenimiento   551.73     25

In [ ]:
df_productos["Categoria"]

0         Accesorios
1              Hogar
2         Accesorios
3        Electrónica
4        Electrónica
5            Oficina
6        Electrónica
7         Accesorios
8            Oficina
9    Entretenimiento
Name: Categoria, dtype: object

In [ ]:
df_productos["Categoria"].unique()

array(['Accesorios', 'Hogar', 'Electrónica', 'Oficina', 'Entretenimiento'],
      dtype=object)

In [ ]:
set(df_productos["Categoria"])

{'Accesorios', 'Electrónica', 'Entretenimiento', 'Hogar', 'Oficina'}

In [ ]:
#Aplicando filtro

df_productos[df_productos["Categoria"] == "Accesorios"]

  Nombre de producto   Categoria   Precio  Stock
0             Tablet  Accesorios   190.11     23
2              Mouse  Accesorios   542.15     20
7         Smartwatch  Accesorios  1193.70     57

In [ ]:
#Aplicamos filtro por cantidad
df_productos[df_productos["Stock"]>60]

  Nombre de producto    Categoria   Precio  Stock
1            Teclado        Hogar  1444.15     93
4             Router  Electrónica  1218.32     77
6            Monitor  Electrónica  1101.57     95

In [ ]:
df_productos.shape

(10, 4)

In [ ]:
#Creamos una variable donde almacenar el resultado del filtro

stock_mayor_60 = df_productos[df_productos["Stock"]>60]

stock_mayor_60

  Nombre de producto    Categoria   Precio  Stock
1            Teclado        Hogar  1444.15     93
4             Router  Electrónica  1218.32     77
6            Monitor  Electrónica  1101.57     95

In [ ]:
stock_mayor_60.shape

(3, 4)

In [ ]:
df_productos[(df_productos["Categoria"]=="Electrónica") & (df_productos["Stock"]>70)]

  Nombre de producto    Categoria   Precio  Stock
4             Router  Electrónica  1218.32     77
6            Monitor  Electrónica  1101.57     95

# ILOC y LOC

***LOC*** selecciona datos utilizando nombres o etiquetas de filas y columnas, mientras que ***ILOC*** utiliza posiciones numéricas enteras (comenzando desde 0, como las listas tradicionales).

In [195]:
df_productos

                          Categoria   Precio  Stock
Nombre de producto
Tablet                         Casa   190.11     23
Teclado                       Hogar  1444.15     93
Mouse                          Casa   542.15     20
Cámara                  Electrónica   259.38     10
Router                  Electrónica  1218.32     77
Auriculares                 Oficina   550.09     53
Monitor                 Electrónica  1101.57     95
Smartwatch                     Casa  1193.70     57
Webcam                      Oficina  1302.93     47
Altavoz             Entretenimiento   551.73     25

In [ ]:
df_productos.iloc[6]

Nombre de producto        Monitor
Categoria             Electrónica
Precio                    1101.57
Stock                          95
Name: 6, dtype: object

In [ ]:
df_productos.iloc[2:6]

  Nombre de producto    Categoria   Precio  Stock
2              Mouse   Accesorios   542.15     20
3             Cámara  Electrónica   259.38     10
4             Router  Electrónica  1218.32     77
5        Auriculares      Oficina   550.09     53

In [ ]:
df_productos.iloc[:5]

  Nombre de producto    Categoria   Precio  Stock
0             Tablet   Accesorios   190.11     23
1            Teclado        Hogar  1444.15     93
2              Mouse   Accesorios   542.15     20
3             Cámara  Electrónica   259.38     10
4             Router  Electrónica  1218.32     77

In [ ]:
df_productos.iloc[5:]

                          Categoria   Precio  Stock
Nombre de producto
Auriculares                 Oficina   550.09     53
Monitor                 Electrónica  1101.57     95
Smartwatch                     Casa  1193.70     57
Webcam                      Oficina  1302.93     47
Altavoz             Entretenimiento   551.73     25

In [218]:
# df_productos = df_productos.reset_index()
df_productos = df_productos.set_index("Nombre de producto")

In [198]:
display(df_productos)

                          Categoria   Precio  Stock
Nombre de producto
Tablet                         Casa   190.11     23
Teclado                       Hogar  1444.15     93
Mouse                          Casa   542.15     20
Cámara                  Electrónica   259.38     10
Router                  Electrónica  1218.32     77
Auriculares                 Oficina   550.09     53
Monitor                 Electrónica  1101.57     95
Smartwatch                     Casa  1193.70     57
Webcam                      Oficina  1302.93     47
Altavoz             Entretenimiento   551.73     25

In [ ]:
df_productos.loc["Router"]

Categoria    Electrónica
Precio           1218.32
Stock                 77
Name: Router, dtype: object

In [ ]:
df_productos.loc["Mouse":]

                          Categoria   Precio  Stock
Nombre de producto
Mouse                    Accesorios   542.15     20
Cámara                  Electrónica   259.38     10
Router                  Electrónica  1218.32     77
Auriculares                 Oficina   550.09     53
Monitor                 Electrónica  1101.57     95
Smartwatch               Accesorios  1193.70     57
Webcam                      Oficina  1302.93     47
Altavoz             Entretenimiento   551.73     25

In [ ]:
df_productos.loc[:"Monitor"]

                      Categoria   Precio  Stock
Nombre de producto
Tablet               Accesorios   190.11     23
Teclado                   Hogar  1444.15     93
Mouse                Accesorios   542.15     20
Cámara              Electrónica   259.38     10
Router              Electrónica  1218.32     77
Auriculares             Oficina   550.09     53
Monitor             Electrónica  1101.57     95

In [206]:
df_productos.loc["Tablet":"Router"]

                      Categoria   Precio  Stock
Nombre de producto
Tablet                     Casa   190.11     23
Teclado                   Hogar  1444.15     93
Mouse                      Casa   542.15     20
Cámara              Electrónica   259.38     10
Router              Electrónica  1218.32     77

In [205]:
df_productos.loc[["Tablet","Webcam"],["Precio","Stock"]]

                     Precio  Stock
Nombre de producto
Tablet               190.11     23
Webcam              1302.93     47

In [208]:
casa = df_productos[df_productos["Categoria"]=="Casa"]

In [209]:
df_productos.loc[casa.index,["Precio","Stock"]]

                     Precio  Stock
Nombre de producto
Tablet               190.11     23
Mouse                542.15     20
Smartwatch          1193.70     57

In [210]:
df_productos

                          Categoria   Precio  Stock
Nombre de producto
Tablet                         Casa   190.11     23
Teclado                       Hogar  1444.15     93
Mouse                          Casa   542.15     20
Cámara                  Electrónica   259.38     10
Router                  Electrónica  1218.32     77
Auriculares                 Oficina   550.09     53
Monitor                 Electrónica  1101.57     95
Smartwatch                     Casa  1193.70     57
Webcam                      Oficina  1302.93     47
Altavoz             Entretenimiento   551.73     25

In [211]:
df_productos.loc[casa.index,"Categoria"] = "Cosas"

In [212]:
df_productos

                          Categoria   Precio  Stock
Nombre de producto
Tablet                        Cosas   190.11     23
Teclado                       Hogar  1444.15     93
Mouse                         Cosas   542.15     20
Cámara                  Electrónica   259.38     10
Router                  Electrónica  1218.32     77
Auriculares                 Oficina   550.09     53
Monitor                 Electrónica  1101.57     95
Smartwatch                    Cosas  1193.70     57
Webcam                      Oficina  1302.93     47
Altavoz             Entretenimiento   551.73     25

Desafio:

1. Cargar un archivo .csv con feedback de clientes y crear un dataframe
2. Usar un LLM para clasificar el sentimiento de cada feedback (positivo, negativo, neutro)
3. Agregar esa clasificación al DataFrame

In [213]:
!pip install -q Groq

In [214]:
import os
from google.colab import userdata
from groq import Groq

os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

client_groq = Groq()

In [215]:
import pandas as pd

In [216]:
#Etapa 1
df_reviews=pd.read_csv("/content/reviews.csv")

In [219]:
df_reviews.head()

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0

In [220]:
columna_de_reviews = df_reviews["reviewText"]

In [221]:
columna_de_reviews

0     it works as expected. I should have sprung for...
1     This think has worked out great.Had a diff. br...
2     Bought it with Retail Packaging, arrived legit...
3     It's mini storage.  It doesn't do anything els...
4     I have it in my phone and it never skips a bea...
5     It works, but file writes are a bit slower tha...
6     I bought 2 of those SanDisk 32 GB microSD , us...
7     The memory card is an excellent condition and ...
8     I bougth this micro SD card after some trubles...
9     Ordered this for a Galaxy S3.  Lasted a few mo...
10    more like 8mb/s in my Note 10.1 and that's usi...
11    I used this for a few months in my phone, then...
12    everything about it was great, except for the ...
13    Used in my phone it's plenty fast and works ju...
14    This card advertises itself as UHS1 but it's a...
15    I bought this SD card for my android phone thi...
16    good card. work as describes. haven't had any ...
17    I got this because I just couldn't pass up the...
18    It works but the actual R/W speeds are 18/8 MB...
19    Does it's job and fairly cheap for what it's w...
20    Still don't feel is very fast or is just my ph...
21    I bought 64GB version of the card to use with ...
22    I have an old SanDisk SD card that still works...
23    Used it in my Galaxy Note 2 for the past 16 mo...
24    Worked great in my galaxy s4--until it didn't ...
25    I bought this on August of 2013.  As of April ...
26    So this product is a large disappointment...bo...
27    I will keep it short and sweet for potential b...
28    The package arrived on time, it's very well pa...
29    Does what it says. Hasn't broken yet, and I ho...
30    Thus microSD card worked fine for a year in my...
31    I think this is probably a fine product, but i...
32    I have two of these and use them for my Galazy...
33    I join the long list of customers who have had...
34    I do not get the advertised speed of 30MB/s, m...
35    the micro sd works great as described. but bew...
36    than i expected. I don't know if it would kill...
37    Reliable and inexpensive. However, it's quite ...
38    I bought this primarily to use in my Surface P...
39    I really don't know what to think about this I...
Name: reviewText, dtype: object

In [223]:
#Etapa 2

lista_de_analisis=[]
for numero, review in enumerate(columna_de_reviews):
    respuesta = client_groq.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
                {
                    "role": "user",
                    "content": f""" Debes analizar la reseña que yo te envio y retornar un analisis de sentimiento. Debes responder
                    con: Positiva, Negativa o Neutra. Ejemplo:

                    Me encanto el producto -> Positiva
                    El producto no es nada especial -> Neutra
                    No me gusto el producto -> Negativa

                    Debes responder solamente una de esas tres opciones (Positiva, Neutra o Negativa) No agregues texto o explicaciones.
                    Limitate a únicamente una de esas tres palabras

                    Reseña: {review}"""

                }

            ]
        )
    texto = respuesta.choices[0].message.content

    print(f"Review {numero}: {review} -> Sentimiento: {texto}")
    lista_de_analisis.append(texto)

Review 0: it works as expected. I should have sprung for the higher capacity.  I think its made a bit cheesier than the earlier versions; the paint looks not as clean as before -> Sentimiento: Neutra
Review 1: This think has worked out great.Had a diff. bran 64gb card and if went south after 3 months.This one has held up pretty well since I had my S3, now on my Note3.*** update 3/21/14I've had this for a few months and have had ZERO issue's since it was transferred from my S3 to my Note3 and into a note2. This card is reliable and solid!Cheers! -> Sentimiento: Positiva
Review 2: Bought it with Retail Packaging, arrived legit, in a orange envelope, english version not asian like the picture shows. arrived quickly, bought a 32 and 16 both retail packaging for my htc one sv and Lg Optimus, both cards in working order, probably best price you'll get for a nice sd card -> Sentimiento: Positiva
Review 3: It's mini storage.  It doesn't do anything else and it's not supposed to.  I purchased it to add additional storage to my Microsoft Surface Pro tablet which only come in 64 and 128 GB.  It does what it's supposed to and SanDisk has a long standing reputation that speaks for itself. -> Sentimiento: Positiva
Review 4: I have it in my phone and it never skips a beat. File transfers are speedy and have not had any corruption issues or memory fade issues as I would expect from the Sandisk brand. Great card to own. Why entrust your precious files to a slightly cheaper piece of crap? If you lose everything can you forgive yourself for not spending the extra couple bucks on a trusted product that goes through good QA? -> Sentimiento: Positiva
Review 5: It works, but file writes are a bit slower than expected on a USB3 reader.Also, both reads and writes are FASTER with the card inside the standard-size SD adapter (15 MB/s vs 10 write; 45 MB/s vs 22 MB/s read) on the same card reader.  Can't figure why... -> Sentimiento: Neutra
Review 6: I bought 2 of those SanDisk 32 GB microSD , used them on my Galaxy Note and Galaxy S4First one , my phone started saying it was removed , then recognize it again :) then diedI thought it's just a luck , plugged in the 2nd one :) stayed for about 2 months and died suddenly ! and lost everythingnever buying from SanDisk again .. ever -> Sentimiento: Negativa
Review 7: The memory card is an excellent condition and work as described. Dependable and easy to use. An excellent choice for the enthusiast who requires more storage. -> Sentimiento: Positiva
Review 8: I bougth this micro SD card after some trubles with other that i got from Kingston, i can tell that SanDisk is other quality, this is the best, my i9300 phone can read a 64GB very fast, the dta transfer speed from my pc to my is amazing, if you are looking for additional storage to you phone, for music, pictures and other type of files, this is for you.Pros-Very good quality materials of construction-Amazing speedUpdate after one year this memory is damaged I can not delete or put new files on it, I can not format this memory, I tried to format with my phone, with my pc, with a camera and nothing, now this is like a 64gb cd, the data in the memory is only available to read but I can not move, or delete it, I bought this memory to be used to backup all my data of my android device but now is only a readable memory I can not write data on it any more, I hope sandisk make a better products in the future!!! Total disagree I will buy a Samsung memory card expected a better quality. -> Sentimiento: Negativa
Review 9: Ordered this for a Galaxy S3.  Lasted a few months and then broke.  Is not accessible on several different PC's.Says "limited lifetime" warranty - BS.  You have ONE MONTH for Eco Zone.  Not only did I lose pictures but now I am out $$ because of a crappy return policy.In the future I will be buying Kingston, not Sandisk.-----------------Update:  Amazon Customer service made good and refunded my purchase price.  I still will not be buying any more Sandisk memory cards however... -> Sentimiento: Negativa
Review 10: more like 8mb/s in my Note 10.1 and that's using SanDisk's own app. A bit faster in my Note II, but still a disappointment for devices with quad core processors. Not sure if it's the card or the device, so benefit of the doubt and four stars. -> Sentimiento: Neutra
Review 11: I used this for a few months in my phone, then it decided to quit mounting. I lost some pictures of pets who died shortly after. I got a replacement card, but I had to send in the old one, giving up any chance of recovering its contents. The new one's worked fine, but failing after 3 months in inexcusable. -> Sentimiento: Negativa
Review 12: everything about it was great, except for the adapter.  It was to tight i had to use a tool to take it back out of the adapter causing me to chip it. so my fault i guess, but i also bought a 16gb version and the adapter for that one was fine. -> Sentimiento: Neutra
Review 13: Used in my phone it's plenty fast and works just like it should. Unexpectedly comes with mini and full SD card size adapters, which is nice. &#34;Fool-proof&#34; packaging or whatever it was, that was laughable. Packaging was decent it just shouldn't have bragged about being impossible to mess up when I messed it up. -> Sentimiento: Positiva
Review 14: This card advertises itself as UHS1 but it's actually UHS50.This means that it will not go up to SDR104 speeds/throughput.Not necessary bad, just false advertising. -> Sentimiento: Negativa
Review 15: I bought this SD card for my android phone thinking that a class 10 will be faster and more reliable than others. it turns out, the difference in class doesn't really matter at least for Android phones. didn't really worth the price difference -> Sentimiento: Negativa
Review 16: good card. work as describes. haven't had any issue with it or going pass metal detectors. no lost files or missing files. -> Sentimiento: Positiva
Review 17: I got this because I just couldn't pass up the deal, $17.99. It has been incredibly fast in my HTC Sensation 4g. Pictures are taken and saved instantaneously. Only had it a few days, but have been very happy. Shipping was fast and the packaging was easy to open which is always great in my book. Only issue I had was I had to format it on my computer first before my phone was able to recognize it. -> Sentimiento: Positiva
Review 18: It works but the actual R/W speeds are 18/8 MB/s, not even Class 10. It should be marketed as "Sandisk Basic", not Sandisk Ultra", unless they mean ultra slow. Now is 2014 and there is no excuse for such slow card from Sandisk.*** UPDATE ***I have redone the test with NotePro 12.2" instead of using non UHS-I PC and the latest results are 32/8.6MB/s. Since the read speed hits 30, I believe the device is DHS-I ready. Still underwhelmed by the write speed though. -> Sentimiento: Negativa
Review 19: Does it's job and fairly cheap for what it's worth. I had to return my first one and exchange it for another because the first one was defective. Sandisk really needs to do better quality assurance on their products. The second one works perfectly fine. I use it for my GoPro camera. -> Sentimiento: Neutra
Review 20: Still don't feel is very fast or is just my phone, I guess I will need to remove it and run some R/W tests. Still Its ok. -> Sentimiento: Neutra
Review 21: I bought 64GB version of the card to use with GoPro Hero 3 black edition.  It didn't work out.  The card worked OK if camera was set to resolution with lower bit rates.  E.g. worked fine in 720p with protune on, or 1080p with protune off.  However, in 1080p with protune on (bitrate is just shy of 6 MB/s in this mode -- much higher then with protune turned off) it was nothing but trouble.  Camera would sometime work, and sometime randomly stop recording for no obvious reason.  I first suspected camera, but testing with different SD cards, it ended up being SanDisk's card that was at fault.  My spare card, an old and cheap 16GB PNY (also class 10), worked just fine under same conditions and with same camera settings.Once it was obvious it was problem with the card, I found people on GoPro's forums that had trouble with this specific card as well (well, you always find these only after you figure it out for yourself, right?).  Anyhow, I did some speed tests with the card by doing simple write of 1GB file full of zeros using Unix dd utility to copy 1GB of zeros from /dev/zero (where else would you find that many zeros ;-) onto a file on the card.  The result was that on average, SanDisk's card would manage about 10.2 MB/s.  Just barely above the bar for class 10 card.  However, that was average over 1GB.  During the write test, the speed was oscillating with many spikes and drops.  Drops were as low as 7MB/s.  Uh.  I thought write speed of class 10 card should never dip below 10 MB/s?  For comparison, my old cheap class 10 PNY card was chugging along at constant 13 MB/s under the same test.  No spikes and no drops in speed.The card will probably work fine in most devices, as bitrates when recording 1080p video are often low enough and/or camera might have huge buffer.  But if you want to use it to record video at high bitrates, and your device doesn't have huge buffer to compensate for speed bumps of this card, you may run into trouble.  Be wary of using it in Hero3 in modes that have higher bit rates (e.g. 1080p with protune enabled).SanDisk's website lists part numbers as SDSDQUI-064G with adapter, and SDSDQUA-064G without adapter.  This conflicts with product description on Amazon.  While this is likely just Amazon not getting product description right again (a bit too common thing), it's interesting to note.[Update Apr 20 2013]:Some numbers from testing the card.  The test is extremely simple.  Write out 1GB of zeros onto the card using standard Unix dd command to read 128KB blocks of zeroes from special device /dev/zero and write it onto the card.  128KB * 8192 = 1GB.  dd displays transfer stats once it finishes.  While dd was running, I run iostat in second terminal displaying 1 second interval stats as a measure of current speed.  This was done on the Mac.  dd command line can be used as-is to repeat test on Linux system, however iostat command is different on Linux and would need to be modified slightly.  I choose 128KB block size, as that seems to be what device drivers merges sequential writes into anyhow.  Using different block sizes, results are comparable.$ dd if=/dev/zero of=test bs=131072 count=81928192+0 records in8192+0 records out1073741824 bytes transferred in 101.578307 secs (10570582 bytes/sec)So, 10 MB/s and all is good? Right? Wrong! iostat running in parallel with above dd command recorded this:$ iostat -d -w 1 disk2disk2KB/t tps MB/s123.11 76 9.12116.61 185 21.04122.94 49 5.88128.00 41 5.12128.00 89 11.11128.00 134 16.73128.00 69 8.61128.00 61 7.62128.00 99 12.36[ ... and so on until dd finishes writing 1GB of zeros to the card ... ]IMO, the last column should never dip under 10MB/s for card labeled class-10.For comparison, same test run against Samsung Pro 64GB micro-SD card:$ dd if=/dev/zero of=test bs=131072 count=81928192+0 records in8192+0 records out1073741824 bytes transferred in 52.869111 secs (20309436 bytes/sec)$ iostat -d -w 1 disk2disk2KB/t tps MB/s125.30 138 16.86117.73 157 18.03123.04 150 18.00128.00 159 19.86128.00 156 19.47126.45 160 19.73128.00 150 18.72128.00 154 19.22128.00 153 19.11[ ... and so on until dd finishes writing 1GB of zeros to the card ... ]So, Samsung is on average 2x faster, but more importantly it's speed is much more constant.  And critically important, it never dips under 10MB/s. -> Sentimiento: Negativa
Review 22: I have an old SanDisk SD card that still works. I thought their new cards would be just as reliable, but I was wrong.The microsd card failed yesterday inside my phone. I used the adapter to connect it to my computer, but it wouldn't mount.I bought this directly from Amazon and not a third party vendor, so I know it's genuine SanDisk. -> Sentimiento: Negativa
Review 23: Used it in my Galaxy Note 2 for the past 16 months. All the sudden it is no longer writable. I tried many ways to reformat the card. Even Windows says format successful but all files remain after I remove and re-insert the card. Since I have private files in the card I'm not able to delete. I do not want to sent it back to SanDisk for replacement. -> Sentimiento: Negativa
Review 24: Worked great in my galaxy s4--until it didn't work at all for some unknown reason. Used it for about 4 months before it crapped out. BACK UP YOUR DATA WITH ALL THESE THINGS, THOUGH.... -> Sentimiento: Negativa
Review 25: I bought this on August of 2013.  As of April 2014 the card stopped functioning.  It can still be read, but the writing capability is gone.  That's less than one year.  I'm extremely disappointed in the longevity of this card.  My usage of it has been on my Galaxy S4.  I have about 40Gb of data in it.  Guess I'm going to have to look for another card that has a longer lifespan than this one. -> Sentimiento: Negativa
Review 26: So this product is a large disappointment...bought it to use in my tablet but the card is forever getting corrupted....I've reformatted the card a few times but it's to the point now that even a reformat doesn't work..  Wasted money...don't recommend purchasing. -> Sentimiento: Negativa
Review 27: I will keep it short and sweet for potential buyers looking for facts and not b.s.I own two of the 32gb size of these cards for about 3 months now. They do work fairly well with cell phones and tablets, yet not so good with cameras, in fact these cards failed to work with my GoPro Hero3 camera and the customer service rep from Gopro claimed (and I happen to agree with him) that this card is not a true class 10 card let alone UHS-1.Benchmarks with my evo 4g with all allocation sizes the write speed never passed beyond 8mb/s while read speeds wondered around 25mb/s far below advertised speeds, well write speeds arent technically advertised (probably because they are of class 4 level)Benchmarks with crystal mark reported speeds even lower (due to adapter) with write speeds around 6mb/s while read speeds wondered around 20mb/s.Needless to say, if you are not worried about speeds and only about storage, these are perfect. If you want to use them for shooting high definition raw footage however, I suggest you not to loose your money on this, because even if your write speeds are around 10mb/s as the card begins to decay it will slow down to become useless.Again this review is based on GoPro camera and high definition raw recording.. For cell phones or for storage it works perfectly well with a bit of false advertisement.. -> Sentimiento: Negativa
Review 28: The package arrived on time, it's very well packed and it's got an adapter. It works perfectly with my phone, though it doesn't allow a computer format, once it's been on the phone, so it asks you to erase everything before you use it on a computer. So if you're planning on buying this for different purposes and devices, gotta be aware of this. I just need for my phone, so I transfer files with my usb cable, that works just right. I also give it a 3 star because it says there are 64gb, but even when it's totally formatted it only reaches to 60gb..sooo, I don't know where my other 4 gb are...anyways, overall it's working well. I do think it's expensive for what it is. -> Sentimiento: Neutra
Review 29: Does what it says. Hasn't broken yet, and I hope it doesn't break. I've had luck with this brand before. Usually get bored with the product before it breaks. -> Sentimiento: Positiva
Review 30: Thus microSD card worked fine for a year in my Samsumg Note II. I mostly used it to listed to downloaded music from Spotify. It has actually failed &#34;twice&#34;. When it failed the first time (the phone couldn't &#34;see&#34; that I had a card installed) I thought maybe something had merely corrupted it, so I formatted it, put it back in my phone, and re-downloaded all my playlists. It worked for two months and then failed again. I don't plan to try formatting it again, I'll switch to a different brand of card. -> Sentimiento: Negativa
Review 31: I think this is probably a fine product, but it wasn't compatible with my Samsung Galaxy S3 phone. Formatted as exFAT (as it came from the factory), didn't work at all, but that's a known problem with the GS3. But even after reformatting to FAT32, the card caused my phone to reboot multiple times. -> Sentimiento: Negativa
Review 32: I have two of these and use them for my Galazy Note 2. It's great having the flexibility to keep extra storage with you for your 'phablet'.So far they have done what they are intended to do. -> Sentimiento: Positiva
Review 33: I join the long list of customers who have had their SanDisk die on them.  Customer service from SanDisk has been helpful.  They pay for UPS shipping for the return and promise a 7-10 day turn around once the defective disk has been returned.  Still it's a pain to deal with and I lost some photographs.UPDATE: SanDisk sent me a replacement and it seems to be working.  If the replacement goes bad, I'll be back to complain:)SECOND UPDATE: All is well with the replacement so I'm giving it three stars. -> Sentimiento: Neutra
Review 34: I do not get the advertised speed of 30MB/s, more like a 200-300KB/s on my Galaxy S4. At least it gives me a lot of extra storage space, for a phone it works nicely if you don't need to transfer big files. -> Sentimiento: Neutra
Review 35: the micro sd works great as described. but beware that the micro sd adapters are faulty. the micro sd will get stuck in the adapter. you will have to carefully rip apart the adapter to get the micro sd out thus damaging the apapter. -> Sentimiento: Negativa
Review 36: than i expected. I don't know if it would kill any manufacturers to actually have a memory card or stick or device to actually HAVE Available the advertised capacity. Fortunately l learned that the advertised and actual available memory are TWO SEPARATE THINGS before i bought it, always scroll down and read the technical spec of a device or anything before you buy as that way ideally, your actually informed. Let the buyer beware, is more appropriate every day as most things are not exactly as they seem. And if it's food and cheap, it's likely cancer causing and don't feed your body and your car in the same place. -> Sentimiento: Negativa
Review 37: Reliable and inexpensive. However, it's quite slow, far, far slower than the 64GB samsung pro microsdxc. The Samsung works well for interactive use while I would only use this Sandisk card for applications where speed isn't important. -> Sentimiento: Neutra
Review 38: I bought this primarily to use in my Surface Pro. It would randomly dismount itself. I do not know if it was the Surface's fault or the card's fault. Upon doing a little internet searching, I found this to be a common problem with Sandisk cards and the Surface Pro. I used another brand microSDXC and it has worked fine. -> Sentimiento: Negativa
Review 39: I really don't know what to think about this I got it thinking it would solve my memory problems but that's not the case turns out you can only put certain things on this and of course none of the thingsthat are eating up your memory on.your will go there is a way to swap your internal memory for your external card but it's not easy and you have to root  your phone -> Sentimiento: Negativa

In [230]:
lista_de_analisis

['Neutra',
 'Positiva',
 'Positiva',
 'Positiva',
 'Positiva',
 'Neutra',
 'Negativa',
 'Positiva',
 'Negativa',
 'Negativa',
 'Neutra',
 'Negativa',
 'Neutra',
 'Positiva',
 'Negativa',
 'Negativa',
 'Positiva',
 'Positiva',
 'Negativa',
 'Neutra',
 'Neutra',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Neutra',
 'Positiva',
 'Negativa',
 'Negativa',
 'Positiva',
 'Neutra',
 'Neutra',
 'Negativa',
 'Negativa',
 'Neutra',
 'Negativa',
 'Negativa']

In [231]:
#Etapa 3

df_reviews["Sentimiento"] = lista_de_analisis

df_reviews.head()

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote,Sentimiento
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0,Neutra
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0,Positiva
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0,Positiva
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0,Positiva
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0,Positiva

# Clase Número 6 - Gestión de Errores

In [233]:
edad = int(input("Ingrese su edad"))

Ingrese su edadcr

ValueError: invalid literal for int() with base 10: 'cr'

In [241]:
try:
  edad = int(input("Ingrese su edad "))
  print(f"Su edad es {edad}")
except ValueError as e:
  print("Ha ocurrido un error")
  print("El error es: ", e)
finally:
  print("Programa finalizado")

Ingrese su edad asd
Ha ocurrido un error
El error es:  invalid literal for int() with base 10: 'asd'
Programa finalizado

## Análisis Negativos para Categorización

In [242]:
!pip install -q Groq

In [243]:
import os
from google.colab import userdata
from groq import Groq

os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

client_groq = Groq()

In [244]:
import pandas as pd

In [245]:
df_reviews=pd.read_csv("/content/reviews.csv")

In [246]:
df_reviews.head()

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0

In [247]:
columna_de_reviews = df_reviews["reviewText"]

In [248]:
lista_de_analisis=[]
for numero, review in enumerate(columna_de_reviews):
    respuesta = client_groq.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
                {
                    "role": "user",
                    "content": f""" Debes analizar la reseña que yo te envio y retornar un analisis de sentimiento. Debes responder
                    con: Positiva, Negativa o Neutra. Ejemplo:

                    Me encanto el producto -> Positiva
                    El producto no es nada especial -> Neutra
                    No me gusto el producto -> Negativa

                    Debes responder solamente una de esas tres opciones (Positiva, Neutra o Negativa) No agregues texto o explicaciones.
                    Limitate a únicamente una de esas tres palabras

                    Reseña: {review}"""

                }

            ]
        )
    texto = respuesta.choices[0].message.content

    print(f"Review {numero}: {review} -> Sentimiento: {texto}")
    lista_de_analisis.append(texto)

Review 0: it works as expected. I should have sprung for the higher capacity.  I think its made a bit cheesier than the earlier versions; the paint looks not as clean as before -> Sentimiento: Neutra
Review 1: This think has worked out great.Had a diff. bran 64gb card and if went south after 3 months.This one has held up pretty well since I had my S3, now on my Note3.*** update 3/21/14I've had this for a few months and have had ZERO issue's since it was transferred from my S3 to my Note3 and into a note2. This card is reliable and solid!Cheers! -> Sentimiento: Positiva
Review 2: Bought it with Retail Packaging, arrived legit, in a orange envelope, english version not asian like the picture shows. arrived quickly, bought a 32 and 16 both retail packaging for my htc one sv and Lg Optimus, both cards in working order, probably best price you'll get for a nice sd card -> Sentimiento: Positiva
Review 3: It's mini storage.  It doesn't do anything else and it's not supposed to.  I purchased it to add additional storage to my Microsoft Surface Pro tablet which only come in 64 and 128 GB.  It does what it's supposed to and SanDisk has a long standing reputation that speaks for itself. -> Sentimiento: Positiva
Review 4: I have it in my phone and it never skips a beat. File transfers are speedy and have not had any corruption issues or memory fade issues as I would expect from the Sandisk brand. Great card to own. Why entrust your precious files to a slightly cheaper piece of crap? If you lose everything can you forgive yourself for not spending the extra couple bucks on a trusted product that goes through good QA? -> Sentimiento: Positiva
Review 5: It works, but file writes are a bit slower than expected on a USB3 reader.Also, both reads and writes are FASTER with the card inside the standard-size SD adapter (15 MB/s vs 10 write; 45 MB/s vs 22 MB/s read) on the same card reader.  Can't figure why... -> Sentimiento: Neutra
Review 6: I bought 2 of those SanDisk 32 GB microSD , used them on my Galaxy Note and Galaxy S4First one , my phone started saying it was removed , then recognize it again :) then diedI thought it's just a luck , plugged in the 2nd one :) stayed for about 2 months and died suddenly ! and lost everythingnever buying from SanDisk again .. ever -> Sentimiento: Negativa
Review 7: The memory card is an excellent condition and work as described. Dependable and easy to use. An excellent choice for the enthusiast who requires more storage. -> Sentimiento: Positiva
Review 8: I bougth this micro SD card after some trubles with other that i got from Kingston, i can tell that SanDisk is other quality, this is the best, my i9300 phone can read a 64GB very fast, the dta transfer speed from my pc to my is amazing, if you are looking for additional storage to you phone, for music, pictures and other type of files, this is for you.Pros-Very good quality materials of construction-Amazing speedUpdate after one year this memory is damaged I can not delete or put new files on it, I can not format this memory, I tried to format with my phone, with my pc, with a camera and nothing, now this is like a 64gb cd, the data in the memory is only available to read but I can not move, or delete it, I bought this memory to be used to backup all my data of my android device but now is only a readable memory I can not write data on it any more, I hope sandisk make a better products in the future!!! Total disagree I will buy a Samsung memory card expected a better quality. -> Sentimiento: Negativa
Review 9: Ordered this for a Galaxy S3.  Lasted a few months and then broke.  Is not accessible on several different PC's.Says "limited lifetime" warranty - BS.  You have ONE MONTH for Eco Zone.  Not only did I lose pictures but now I am out $$ because of a crappy return policy.In the future I will be buying Kingston, not Sandisk.-----------------Update:  Amazon Customer service made good and refunded my purchase price.  I still will not be buying any more Sandisk memory cards however... -> Sentimiento: Negativa
Review 10: more like 8mb/s in my Note 10.1 and that's using SanDisk's own app. A bit faster in my Note II, but still a disappointment for devices with quad core processors. Not sure if it's the card or the device, so benefit of the doubt and four stars. -> Sentimiento: Neutra
Review 11: I used this for a few months in my phone, then it decided to quit mounting. I lost some pictures of pets who died shortly after. I got a replacement card, but I had to send in the old one, giving up any chance of recovering its contents. The new one's worked fine, but failing after 3 months in inexcusable. -> Sentimiento: Negativa
Review 12: everything about it was great, except for the adapter.  It was to tight i had to use a tool to take it back out of the adapter causing me to chip it. so my fault i guess, but i also bought a 16gb version and the adapter for that one was fine. -> Sentimiento: Neutra
Review 13: Used in my phone it's plenty fast and works just like it should. Unexpectedly comes with mini and full SD card size adapters, which is nice. &#34;Fool-proof&#34; packaging or whatever it was, that was laughable. Packaging was decent it just shouldn't have bragged about being impossible to mess up when I messed it up. -> Sentimiento: Positiva
Review 14: This card advertises itself as UHS1 but it's actually UHS50.This means that it will not go up to SDR104 speeds/throughput.Not necessary bad, just false advertising. -> Sentimiento: Negativa
Review 15: I bought this SD card for my android phone thinking that a class 10 will be faster and more reliable than others. it turns out, the difference in class doesn't really matter at least for Android phones. didn't really worth the price difference -> Sentimiento: Negativa
Review 16: good card. work as describes. haven't had any issue with it or going pass metal detectors. no lost files or missing files. -> Sentimiento: Positiva
Review 17: I got this because I just couldn't pass up the deal, $17.99. It has been incredibly fast in my HTC Sensation 4g. Pictures are taken and saved instantaneously. Only had it a few days, but have been very happy. Shipping was fast and the packaging was easy to open which is always great in my book. Only issue I had was I had to format it on my computer first before my phone was able to recognize it. -> Sentimiento: Positiva
Review 18: It works but the actual R/W speeds are 18/8 MB/s, not even Class 10. It should be marketed as "Sandisk Basic", not Sandisk Ultra", unless they mean ultra slow. Now is 2014 and there is no excuse for such slow card from Sandisk.*** UPDATE ***I have redone the test with NotePro 12.2" instead of using non UHS-I PC and the latest results are 32/8.6MB/s. Since the read speed hits 30, I believe the device is DHS-I ready. Still underwhelmed by the write speed though. -> Sentimiento: Negativa
Review 19: Does it's job and fairly cheap for what it's worth. I had to return my first one and exchange it for another because the first one was defective. Sandisk really needs to do better quality assurance on their products. The second one works perfectly fine. I use it for my GoPro camera. -> Sentimiento: Neutra
Review 20: Still don't feel is very fast or is just my phone, I guess I will need to remove it and run some R/W tests. Still Its ok. -> Sentimiento: Neutra
Review 21: I bought 64GB version of the card to use with GoPro Hero 3 black edition.  It didn't work out.  The card worked OK if camera was set to resolution with lower bit rates.  E.g. worked fine in 720p with protune on, or 1080p with protune off.  However, in 1080p with protune on (bitrate is just shy of 6 MB/s in this mode -- much higher then with protune turned off) it was nothing but trouble.  Camera would sometime work, and sometime randomly stop recording for no obvious reason.  I first suspected camera, but testing with different SD cards, it ended up being SanDisk's card that was at fault.  My spare card, an old and cheap 16GB PNY (also class 10), worked just fine under same conditions and with same camera settings.Once it was obvious it was problem with the card, I found people on GoPro's forums that had trouble with this specific card as well (well, you always find these only after you figure it out for yourself, right?).  Anyhow, I did some speed tests with the card by doing simple write of 1GB file full of zeros using Unix dd utility to copy 1GB of zeros from /dev/zero (where else would you find that many zeros ;-) onto a file on the card.  The result was that on average, SanDisk's card would manage about 10.2 MB/s.  Just barely above the bar for class 10 card.  However, that was average over 1GB.  During the write test, the speed was oscillating with many spikes and drops.  Drops were as low as 7MB/s.  Uh.  I thought write speed of class 10 card should never dip below 10 MB/s?  For comparison, my old cheap class 10 PNY card was chugging along at constant 13 MB/s under the same test.  No spikes and no drops in speed.The card will probably work fine in most devices, as bitrates when recording 1080p video are often low enough and/or camera might have huge buffer.  But if you want to use it to record video at high bitrates, and your device doesn't have huge buffer to compensate for speed bumps of this card, you may run into trouble.  Be wary of using it in Hero3 in modes that have higher bit rates (e.g. 1080p with protune enabled).SanDisk's website lists part numbers as SDSDQUI-064G with adapter, and SDSDQUA-064G without adapter.  This conflicts with product description on Amazon.  While this is likely just Amazon not getting product description right again (a bit too common thing), it's interesting to note.[Update Apr 20 2013]:Some numbers from testing the card.  The test is extremely simple.  Write out 1GB of zeros onto the card using standard Unix dd command to read 128KB blocks of zeroes from special device /dev/zero and write it onto the card.  128KB * 8192 = 1GB.  dd displays transfer stats once it finishes.  While dd was running, I run iostat in second terminal displaying 1 second interval stats as a measure of current speed.  This was done on the Mac.  dd command line can be used as-is to repeat test on Linux system, however iostat command is different on Linux and would need to be modified slightly.  I choose 128KB block size, as that seems to be what device drivers merges sequential writes into anyhow.  Using different block sizes, results are comparable.$ dd if=/dev/zero of=test bs=131072 count=81928192+0 records in8192+0 records out1073741824 bytes transferred in 101.578307 secs (10570582 bytes/sec)So, 10 MB/s and all is good? Right? Wrong! iostat running in parallel with above dd command recorded this:$ iostat -d -w 1 disk2disk2KB/t tps MB/s123.11 76 9.12116.61 185 21.04122.94 49 5.88128.00 41 5.12128.00 89 11.11128.00 134 16.73128.00 69 8.61128.00 61 7.62128.00 99 12.36[ ... and so on until dd finishes writing 1GB of zeros to the card ... ]IMO, the last column should never dip under 10MB/s for card labeled class-10.For comparison, same test run against Samsung Pro 64GB micro-SD card:$ dd if=/dev/zero of=test bs=131072 count=81928192+0 records in8192+0 records out1073741824 bytes transferred in 52.869111 secs (20309436 bytes/sec)$ iostat -d -w 1 disk2disk2KB/t tps MB/s125.30 138 16.86117.73 157 18.03123.04 150 18.00128.00 159 19.86128.00 156 19.47126.45 160 19.73128.00 150 18.72128.00 154 19.22128.00 153 19.11[ ... and so on until dd finishes writing 1GB of zeros to the card ... ]So, Samsung is on average 2x faster, but more importantly it's speed is much more constant.  And critically important, it never dips under 10MB/s. -> Sentimiento: Negativa
Review 22: I have an old SanDisk SD card that still works. I thought their new cards would be just as reliable, but I was wrong.The microsd card failed yesterday inside my phone. I used the adapter to connect it to my computer, but it wouldn't mount.I bought this directly from Amazon and not a third party vendor, so I know it's genuine SanDisk. -> Sentimiento: Negativa
Review 23: Used it in my Galaxy Note 2 for the past 16 months. All the sudden it is no longer writable. I tried many ways to reformat the card. Even Windows says format successful but all files remain after I remove and re-insert the card. Since I have private files in the card I'm not able to delete. I do not want to sent it back to SanDisk for replacement. -> Sentimiento: Negativa
Review 24: Worked great in my galaxy s4--until it didn't work at all for some unknown reason. Used it for about 4 months before it crapped out. BACK UP YOUR DATA WITH ALL THESE THINGS, THOUGH.... -> Sentimiento: Negativa
Review 25: I bought this on August of 2013.  As of April 2014 the card stopped functioning.  It can still be read, but the writing capability is gone.  That's less than one year.  I'm extremely disappointed in the longevity of this card.  My usage of it has been on my Galaxy S4.  I have about 40Gb of data in it.  Guess I'm going to have to look for another card that has a longer lifespan than this one. -> Sentimiento: Negativa
Review 26: So this product is a large disappointment...bought it to use in my tablet but the card is forever getting corrupted....I've reformatted the card a few times but it's to the point now that even a reformat doesn't work..  Wasted money...don't recommend purchasing. -> Sentimiento: Negativa
Review 27: I will keep it short and sweet for potential buyers looking for facts and not b.s.I own two of the 32gb size of these cards for about 3 months now. They do work fairly well with cell phones and tablets, yet not so good with cameras, in fact these cards failed to work with my GoPro Hero3 camera and the customer service rep from Gopro claimed (and I happen to agree with him) that this card is not a true class 10 card let alone UHS-1.Benchmarks with my evo 4g with all allocation sizes the write speed never passed beyond 8mb/s while read speeds wondered around 25mb/s far below advertised speeds, well write speeds arent technically advertised (probably because they are of class 4 level)Benchmarks with crystal mark reported speeds even lower (due to adapter) with write speeds around 6mb/s while read speeds wondered around 20mb/s.Needless to say, if you are not worried about speeds and only about storage, these are perfect. If you want to use them for shooting high definition raw footage however, I suggest you not to loose your money on this, because even if your write speeds are around 10mb/s as the card begins to decay it will slow down to become useless.Again this review is based on GoPro camera and high definition raw recording.. For cell phones or for storage it works perfectly well with a bit of false advertisement.. -> Sentimiento: Negativa
Review 28: The package arrived on time, it's very well packed and it's got an adapter. It works perfectly with my phone, though it doesn't allow a computer format, once it's been on the phone, so it asks you to erase everything before you use it on a computer. So if you're planning on buying this for different purposes and devices, gotta be aware of this. I just need for my phone, so I transfer files with my usb cable, that works just right. I also give it a 3 star because it says there are 64gb, but even when it's totally formatted it only reaches to 60gb..sooo, I don't know where my other 4 gb are...anyways, overall it's working well. I do think it's expensive for what it is. -> Sentimiento: Neutra
Review 29: Does what it says. Hasn't broken yet, and I hope it doesn't break. I've had luck with this brand before. Usually get bored with the product before it breaks. -> Sentimiento: Positiva
Review 30: Thus microSD card worked fine for a year in my Samsumg Note II. I mostly used it to listed to downloaded music from Spotify. It has actually failed &#34;twice&#34;. When it failed the first time (the phone couldn't &#34;see&#34; that I had a card installed) I thought maybe something had merely corrupted it, so I formatted it, put it back in my phone, and re-downloaded all my playlists. It worked for two months and then failed again. I don't plan to try formatting it again, I'll switch to a different brand of card. -> Sentimiento: Negativa
Review 31: I think this is probably a fine product, but it wasn't compatible with my Samsung Galaxy S3 phone. Formatted as exFAT (as it came from the factory), didn't work at all, but that's a known problem with the GS3. But even after reformatting to FAT32, the card caused my phone to reboot multiple times. -> Sentimiento: Negativa
Review 32: I have two of these and use them for my Galazy Note 2. It's great having the flexibility to keep extra storage with you for your 'phablet'.So far they have done what they are intended to do. -> Sentimiento: Positiva
Review 33: I join the long list of customers who have had their SanDisk die on them.  Customer service from SanDisk has been helpful.  They pay for UPS shipping for the return and promise a 7-10 day turn around once the defective disk has been returned.  Still it's a pain to deal with and I lost some photographs.UPDATE: SanDisk sent me a replacement and it seems to be working.  If the replacement goes bad, I'll be back to complain:)SECOND UPDATE: All is well with the replacement so I'm giving it three stars. -> Sentimiento: Neutra
Review 34: I do not get the advertised speed of 30MB/s, more like a 200-300KB/s on my Galaxy S4. At least it gives me a lot of extra storage space, for a phone it works nicely if you don't need to transfer big files. -> Sentimiento: Neutra
Review 35: the micro sd works great as described. but beware that the micro sd adapters are faulty. the micro sd will get stuck in the adapter. you will have to carefully rip apart the adapter to get the micro sd out thus damaging the apapter. -> Sentimiento: Negativa
Review 36: than i expected. I don't know if it would kill any manufacturers to actually have a memory card or stick or device to actually HAVE Available the advertised capacity. Fortunately l learned that the advertised and actual available memory are TWO SEPARATE THINGS before i bought it, always scroll down and read the technical spec of a device or anything before you buy as that way ideally, your actually informed. Let the buyer beware, is more appropriate every day as most things are not exactly as they seem. And if it's food and cheap, it's likely cancer causing and don't feed your body and your car in the same place. -> Sentimiento: Neutra
Review 37: Reliable and inexpensive. However, it's quite slow, far, far slower than the 64GB samsung pro microsdxc. The Samsung works well for interactive use while I would only use this Sandisk card for applications where speed isn't important. -> Sentimiento: Neutra
Review 38: I bought this primarily to use in my Surface Pro. It would randomly dismount itself. I do not know if it was the Surface's fault or the card's fault. Upon doing a little internet searching, I found this to be a common problem with Sandisk cards and the Surface Pro. I used another brand microSDXC and it has worked fine. -> Sentimiento: Negativa
Review 39: I really don't know what to think about this I got it thinking it would solve my memory problems but that's not the case turns out you can only put certain things on this and of course none of the thingsthat are eating up your memory on.your will go there is a way to swap your internal memory for your external card but it's not easy and you have to root  your phone -> Sentimiento: Negativa

In [249]:
lista_de_analisis

['Neutra',
 'Positiva',
 'Positiva',
 'Positiva',
 'Positiva',
 'Neutra',
 'Negativa',
 'Positiva',
 'Negativa',
 'Negativa',
 'Neutra',
 'Negativa',
 'Neutra',
 'Positiva',
 'Negativa',
 'Negativa',
 'Positiva',
 'Positiva',
 'Negativa',
 'Neutra',
 'Neutra',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Neutra',
 'Positiva',
 'Negativa',
 'Negativa',
 'Positiva',
 'Neutra',
 'Neutra',
 'Negativa',
 'Neutra',
 'Neutra',
 'Negativa',
 'Negativa']

In [251]:
df_reviews
df_reviews["Sentimiento"]

0       Neutra
1     Positiva
2     Positiva
3     Positiva
4     Positiva
5       Neutra
6     Negativa
7     Positiva
8     Negativa
9     Negativa
10      Neutra
11    Negativa
12      Neutra
13    Positiva
14    Negativa
15    Negativa
16    Positiva
17    Positiva
18    Negativa
19      Neutra
20      Neutra
21    Negativa
22    Negativa
23    Negativa
24    Negativa
25    Negativa
26    Negativa
27    Negativa
28      Neutra
29    Positiva
30    Negativa
31    Negativa
32    Positiva
33      Neutra
34      Neutra
35    Negativa
36      Neutra
37      Neutra
38    Negativa
39    Negativa
Name: Sentimiento, dtype: object

In [253]:
df_reviews["Sentimiento"] == "Negativa"

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8      True
9      True
10    False
11     True
12    False
13    False
14     True
15     True
16    False
17    False
18     True
19    False
20    False
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28    False
29    False
30     True
31     True
32    False
33    False
34    False
35     True
36    False
37    False
38     True
39     True
Name: Sentimiento, dtype: bool

In [257]:
df_reviews_negativas = df_reviews[df_reviews["Sentimiento"] == "Negativa"]
df_reviews_negativas.head()

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote,Sentimiento
6,AF24M1HKIZ7QC,B007WTAJTO,"Abdulrahman J. Alrashed ""dr34m3r""","I bought 2 of those SanDisk 32 GB microSD , us...",1375488000,08/03/2013,640,0,0,Negativa
8,A1FKE13D77L3Y3,B007WTAJTO,Abraham Arturo Meza Marin,I bougth this micro SD card after some trubles...,1361232000,19/02/2013,657,0,0,Negativa
9,A1X1FX3NSOFCT3,B007WTAJTO,"Abused Commuter ""abused_commuter""",Ordered this for a Galaxy S3. Lasted a few mo...,1374278400,20/07/2013,506,0,1,Negativa
11,A2RJ7DAL63MN1F,B007WTAJTO,Ace of Sevens,"I used this for a few months in my phone, then...",1391126400,31/01/2014,311,0,0,Negativa
14,APAEBFIM1588A,B007WTAJTO,"Adam Wright ""Electrical Engineer""",This card advertises itself as UHS1 but it's a...,1378684800,09/09/2013,455,1,1,Negativa

In [258]:
reviews_negativas = df_reviews_negativas["reviewText"]
reviews_negativas

6     I bought 2 of those SanDisk 32 GB microSD , us...
8     I bougth this micro SD card after some trubles...
9     Ordered this for a Galaxy S3.  Lasted a few mo...
11    I used this for a few months in my phone, then...
14    This card advertises itself as UHS1 but it's a...
15    I bought this SD card for my android phone thi...
18    It works but the actual R/W speeds are 18/8 MB...
21    I bought 64GB version of the card to use with ...
22    I have an old SanDisk SD card that still works...
23    Used it in my Galaxy Note 2 for the past 16 mo...
24    Worked great in my galaxy s4--until it didn't ...
25    I bought this on August of 2013.  As of April ...
26    So this product is a large disappointment...bo...
27    I will keep it short and sweet for potential b...
30    Thus microSD card worked fine for a year in my...
31    I think this is probably a fine product, but i...
35    the micro sd works great as described. but bew...
38    I bought this primarily to use in my Surface P...
39    I really don't know what to think about this I...
Name: reviewText, dtype: object

In [259]:
reviews_negativas_unidas = "###".join(reviews_negativas)
reviews_negativas_unidas

'I bought 2 of those SanDisk 32 GB microSD , used them on my Galaxy Note and Galaxy S4First one , my phone started saying it was removed , then recognize it again :) then diedI thought it\'s just a luck , plugged in the 2nd one :) stayed for about 2 months and died suddenly ! and lost everythingnever buying from SanDisk again .. ever###I bougth this micro SD card after some trubles with other that i got from Kingston, i can tell that SanDisk is other quality, this is the best, my i9300 phone can read a 64GB very fast, the dta transfer speed from my pc to my is amazing, if you are looking for additional storage to you phone, for music, pictures and other type of files, this is for you.Pros-Very good quality materials of construction-Amazing speedUpdate after one year this memory is damaged I can not delete or put new files on it, I can not format this memory, I tried to format with my phone, with my pc, with a camera and nothing, now this is like a 64gb cd, the data in the memory is only available to read but I can not move, or delete it, I bought this memory to be used to backup all my data of my android device but now is only a readable memory I can not write data on it any more, I hope sandisk make a better products in the future!!! Total disagree I will buy a Samsung memory card expected a better quality.###Ordered this for a Galaxy S3.  Lasted a few months and then broke.  Is not accessible on several different PC\'s.Says "limited lifetime" warranty - BS.  You have ONE MONTH for Eco Zone.  Not only did I lose pictures but now I am out $$ because of a crappy return policy.In the future I will be buying Kingston, not Sandisk.-----------------Update:  Amazon Customer service made good and refunded my purchase price.  I still will not be buying any more Sandisk memory cards however...###I used this for a few months in my phone, then it decided to quit mounting. I lost some pictures of pets who died shortly after. I got a replacement card, but I had to send in the old one, giving up any chance of recovering its contents. The new one\'s worked fine, but failing after 3 months in inexcusable.###This card advertises itself as UHS1 but it\'s actually UHS50.This means that it will not go up to SDR104 speeds/throughput.Not necessary bad, just false advertising.###I bought this SD card for my android phone thinking that a class 10 will be faster and more reliable than others. it turns out, the difference in class doesn\'t really matter at least for Android phones. didn\'t really worth the price difference###It works but the actual R/W speeds are 18/8 MB/s, not even Class 10. It should be marketed as "Sandisk Basic", not Sandisk Ultra", unless they mean ultra slow. Now is 2014 and there is no excuse for such slow card from Sandisk.*** UPDATE ***I have redone the test with NotePro 12.2" instead of using non UHS-I PC and the latest results are 32/8.6MB/s. Since the read speed hits 30, I believe the device is DHS-I ready. Still underwhelmed by the write speed though.###I bought 64GB version of the card to use with GoPro Hero 3 black edition.  It didn\'t work out.  The card worked OK if camera was set to resolution with lower bit rates.  E.g. worked fine in 720p with protune on, or 1080p with protune off.  However, in 1080p with protune on (bitrate is just shy of 6 MB/s in this mode -- much higher then with protune turned off) it was nothing but trouble.  Camera would sometime work, and sometime randomly stop recording for no obvious reason.  I first suspected camera, but testing with different SD cards, it ended up being SanDisk\'s card that was at fault.  My spare card, an old and cheap 16GB PNY (also class 10), worked just fine under same conditions and with same camera settings.Once it was obvious it was problem with the card, I found people on GoPro\'s forums that had trouble with this specific card as well (well, you always find these only after you figure it out for yourself, right?).  Anyhow, I did some speed tests with the card by doing simple write of 1GB file full of zeros using Unix dd utility to copy 1GB of zeros from /dev/zero (where else would you find that many zeros ;-) onto a file on the card.  The result was that on average, SanDisk\'s card would manage about 10.2 MB/s.  Just barely above the bar for class 10 card.  However, that was average over 1GB.  During the write test, the speed was oscillating with many spikes and drops.  Drops were as low as 7MB/s.  Uh.  I thought write speed of class 10 card should never dip below 10 MB/s?  For comparison, my old cheap class 10 PNY card was chugging along at constant 13 MB/s under the same test.  No spikes and no drops in speed.The card will probably work fine in most devices, as bitrates when recording 1080p video are often low enough and/or camera might have huge buffer.  But if you want to use it to record video at high bitrates, and your device doesn\'t have huge buffer to compensate for speed bumps of this card, you may run into trouble.  Be wary of using it in Hero3 in modes that have higher bit rates (e.g. 1080p with protune enabled).SanDisk\'s website lists part numbers as SDSDQUI-064G with adapter, and SDSDQUA-064G without adapter.  This conflicts with product description on Amazon.  While this is likely just Amazon not getting product description right again (a bit too common thing), it\'s interesting to note.[Update Apr 20 2013]:Some numbers from testing the card.  The test is extremely simple.  Write out 1GB of zeros onto the card using standard Unix dd command to read 128KB blocks of zeroes from special device /dev/zero and write it onto the card.  128KB * 8192 = 1GB.  dd displays transfer stats once it finishes.  While dd was running, I run iostat in second terminal displaying 1 second interval stats as a measure of current speed.  This was done on the Mac.  dd command line can be used as-is to repeat test on Linux system, however iostat command is different on Linux and would need to be modified slightly.  I choose 128KB block size, as that seems to be what device drivers merges sequential writes into anyhow.  Using different block sizes, results are comparable.$ dd if=/dev/zero of=test bs=131072 count=81928192+0 records in8192+0 records out1073741824 bytes transferred in 101.578307 secs (10570582 bytes/sec)So, 10 MB/s and all is good? Right? Wrong! iostat running in parallel with above dd command recorded this:$ iostat -d -w 1 disk2disk2KB/t tps MB/s123.11 76 9.12116.61 185 21.04122.94 49 5.88128.00 41 5.12128.00 89 11.11128.00 134 16.73128.00 69 8.61128.00 61 7.62128.00 99 12.36[ ... and so on until dd finishes writing 1GB of zeros to the card ... ]IMO, the last column should never dip under 10MB/s for card labeled class-10.For comparison, same test run against Samsung Pro 64GB micro-SD card:$ dd if=/dev/zero of=test bs=131072 count=81928192+0 records in8192+0 records out1073741824 bytes transferred in 52.869111 secs (20309436 bytes/sec)$ iostat -d -w 1 disk2disk2KB/t tps MB/s125.30 138 16.86117.73 157 18.03123.04 150 18.00128.00 159 19.86128.00 156 19.47126.45 160 19.73128.00 150 18.72128.00 154 19.22128.00 153 19.11[ ... and so on until dd finishes writing 1GB of zeros to the card ... ]So, Samsung is on average 2x faster, but more importantly it\'s speed is much more constant.  And critically important, it never dips under 10MB/s.###I have an old SanDisk SD card that still works. I thought their new cards would be just as reliable, but I was wrong.The microsd card failed yesterday inside my phone. I used the adapter to connect it to my computer, but it wouldn\'t mount.I bought this directly from Amazon and not a third party vendor, so I know it\'s genuine SanDisk.###Used it in my Galaxy Note 2 for the past 16 months. All the sudden it is no longer writable. I tried many ways to reformat the card. Even Windows says format successful but all files remain after I remove and re-insert the card. Since I have private files in the card I\'m not able to delete. I do not want to sent it back to SanDisk for replacement.###Worked great in my galaxy s4--until it didn\'t work at all for some unknown reason. Used it for about 4 months before it crapped out. BACK UP YOUR DATA WITH ALL THESE THINGS, THOUGH....###I bought this on August of 2013.  As of April 2014 the card stopped functioning.  It can still be read, but the writing capability is gone.  That\'s less than one year.  I\'m extremely disappointed in the longevity of this card.  My usage of it has been on my Galaxy S4.  I have about 40Gb of data in it.  Guess I\'m going to have to look for another card that has a longer lifespan than this one.###So this product is a large disappointment...bought it to use in my tablet but the card is forever getting corrupted....I\'ve reformatted the card a few times but it\'s to the point now that even a reformat doesn\'t work..  Wasted money...don\'t recommend purchasing.###I will keep it short and sweet for potential buyers looking for facts and not b.s.I own two of the 32gb size of these cards for about 3 months now. They do work fairly well with cell phones and tablets, yet not so good with cameras, in fact these cards failed to work with my GoPro Hero3 camera and the customer service rep from Gopro claimed (and I happen to agree with him) that this card is not a true class 10 card let alone UHS-1.Benchmarks with my evo 4g with all allocation sizes the write speed never passed beyond 8mb/s while read speeds wondered around 25mb/s far below advertised speeds, well write speeds arent technically advertised (probably because they are of class 4 level)Benchmarks with crystal mark reported speeds even lower (due to adapter) with write speeds around 6mb/s while read speeds wondered around 20mb/s.Needless to say, if you are not worried about speeds and only about storage, these are perfect. If you want to use them for shooting high definition raw footage however, I suggest you not to loose your money on this, because even if your write speeds are around 10mb/s as the card begins to decay it will slow down to become useless.Again this review is based on GoPro camera and high definition raw recording.. For cell phones or for storage it works perfectly well with a bit of false advertisement..###Thus microSD card worked fine for a year in my Samsumg Note II. I mostly used it to listed to downloaded music from Spotify. It has actually failed &#34;twice&#34;. When it failed the first time (the phone couldn\'t &#34;see&#34; that I had a card installed) I thought maybe something had merely corrupted it, so I formatted it, put it back in my phone, and re-downloaded all my playlists. It worked for two months and then failed again. I don\'t plan to try formatting it again, I\'ll switch to a different brand of card.###I think this is probably a fine product, but it wasn\'t compatible with my Samsung Galaxy S3 phone. Formatted as exFAT (as it came from the factory), didn\'t work at all, but that\'s a known problem with the GS3. But even after reformatting to FAT32, the card caused my phone to reboot multiple times.###the micro sd works great as described. but beware that the micro sd adapters are faulty. the micro sd will get stuck in the adapter. you will have to carefully rip apart the adapter to get the micro sd out thus damaging the apapter.###I bought this primarily to use in my Surface Pro. It would randomly dismount itself. I do not know if it was the Surface\'s fault or the card\'s fault. Upon doing a little internet searching, I found this to be a common problem with Sandisk cards and the Surface Pro. I used another brand microSDXC and it has worked fine.###I really don\'t know what to think about this I got it thinking it would solve my memory problems but that\'s not the case turns out you can only put certain things on this and of course none of the thingsthat are eating up your memory on.your will go there is a way to swap your internal memory for your external card but it\'s not easy and you have to root  your phone'

In [261]:
respuestas_cat = client_groq.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "user",
            "content": f"""Eres un analista de datos, te pasaré muchas reseñas separadas por ###
            Quiero que encuentres *exactamente* 5 categorias diferentes para cada tipo de reclamo.
            Quiero que retornes las cinco categorias como una lista de palabras separadas por comas, sin tildes y en minúsculas.
            La respuesta debe ser solamente las cinco categorias, separadas por comas.

            Ejemplo:

                "uso, calidad, estado, duración, aspecto"

                Reseña: {reviews_negativas_unidas}"""
        }
    ]
)

print(respuestas_cat.choices[0].message.content)

calidad, estado, duración, velocidad, compatibilidad

In [263]:
categorias = respuestas_cat.choices[0].message.content

In [264]:
lista_de_categorias = categorias.split(", ")
lista_de_categorias

['calidad', 'estado', 'duración', 'velocidad', 'compatibilidad']

## **Revisando la categorización de las reviews**

### **JSON**

In [265]:
{
    "name": "Chris",
    "age": 23,
    "address": {
        "city": "New York",
        "country": "America"
    },
    "friends": [
        {
            "name": "Emily",
            "hobbies": [
                "biking",
                "music",
                "gaming"
            ]
        },
        {
            "name": "John",
            "hobbies": [
                "soccer",
                "gaming"
            ]
        }
    ]
}

{'name': 'Chris',
 'age': 23,
 'address': {'city': 'New York', 'country': 'America'},
 'friends': [{'name': 'Emily', 'hobbies': ['biking', 'music', 'gaming']},
  {'name': 'John', 'hobbies': ['soccer', 'gaming']}]}

In [281]:
respuestas_cat = client_groq.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
                "role": "user",
                "content": f"""Eres un analista de datos, te pasaré muchas reseñas separadas por "####"
                Quiero que encuentres *exactamente* 5 categorias diferentes para cada tipo de reclamo.
                Las categorias deben ser solo una palabra.
                Despues quiero que me retornes la respuesta en formato JSON con tres claves:
                - "review_original": Aqui va la review original;
                - "review_es": Reseña traducida al español;
                - "categoria": Categoria definida correspondiente a esa reseña.

                Ejemplo:

                {{"review_original": "I didn´t like the color of the product"}}

                La respuesta debe ser SOLO y UNICAMENTE el texto en JSON

                          Reseñas: {reviews_negativas_unidas}"""
            }
       ],
    response_format={"type": "json_object"},
    max_tokens=4096
    )

json_de_reviews_clasificadas = respuestas_cat.choices[0].message.content
print(json_de_reviews_clasificadas)

{
  "review1": {
      "review_original": "I bought 2 of those SanDisk 32 GB microSD , used them on my Galaxy Note and Galaxy S4First one , my phone started saying it was removed , then recognize it again :) then diedI thought it's just a luck , plugged in the 2nd one :) stayed for about 2 months and died suddenly ! and lost everythingnever buying from SanDisk again .. ever",
      "review_es": "Compré 2 de esas tarjetas microSD de SanDisk de 32 GB, las usé en mi Galaxy Note y Galaxy S4. La primera tarjeta, mi teléfono comenzó a decir que había sido retirada, luego la volvió a reconocer y murió. Pensé que era solo mala suerte, así que conecté la segunda tarjeta y duró unos 2 meses y murió de repente. Nunca más compraré de SanDisk... nunca",
      "categoria": "Falla"
   },
   "review2": {
      "review_original": "I bougth this micro SD card after some trubles with other that i got from Kingston, i can tell that SanDisk is other quality, this is the best, my i9300 phone can read a 64GB very fast, the dta transfer speed from my pc to my is amazing, if you are looking for additional storage to you phone, for music, pictures and other type of files, this is for you.",
      "review_es": "Compré esta tarjeta microSD después de algunos problemas con otra que compré de Kingston, puedo decir que SanDisk es de otra calidad, esta es la mejor, mi teléfono i9300 puede leer un 64GB muy rápido, la velocidad de transferencia de datos desde mi pc hasta mi teléfono es impresionante, si buscas almacenamiento adicional para tu teléfono, para música, fotos y otros tipos de archivos, esta es para ti.",
      "categoria": "Calidad"
   },
   "review3": {
      "review_original": "Ordered this for a Galaxy S3.  Lasted a few months and then broke.  Is not accessible on several different PC's.Says 'limited lifetime' warranty - BS.  You have ONE MONTH for Eco Zone.  Not only did I lose pictures but now I am out $$ because of a crappy return policy.",
      "review_es": "Pedí esto para un Galaxy S3. Duró unos meses y luego se rompió. No es accesible en varios PC diferentes. Dice 'garantía de por vida' - tonterías. Tienes UN MES para la zona Eco. No solo perdí fotos, sino que ahora estoy fuera de $$ debido a una política de devolución defectuosa.",
      "categoria": "Garantia"
   },
   "review4": {
      "review_original": "I used this for a few months in my phone, then it decided to quit mounting. I lost some pictures of pets who died shortly after. I got a replacement card, but I had to send in the old one, giving up any chance of recovering its contents.",
      "review_es": "Usé esto durante unos meses en mi teléfono, luego decidió dejar de montar. Perdí algunas fotos de mascotas que murieron poco después. Obtuve una tarjeta de reemplazo, pero tuve que enviar la antigua, renunciando a cualquier posibilidad de recuperar su contenido.",
      "categoria": "Pérdida"
   },
   "review5": {
      "review_original": "This card advertises itself as UHS1 but it's actually UHS50.This means that it will not go up to SDR104 speeds/throughput.Not necessary bad, just false advertising.",
      "review_es": "Esta tarjeta se anuncia como UHS1 pero en realidad es UHS50. Esto significa que no alcanzará velocidades/rendimiento SDR104. No es necesariamente mala, solo publicidad falsa.",
      "categoria": "Publicidad"
   }
}

In [284]:
import json

dic_reviews_negativas_clasificadas = json.loads(json_de_reviews_clasificadas)

In [285]:
dic_reviews_negativas_clasificadas

{'review1': {'review_original': "I bought 2 of those SanDisk 32 GB microSD , used them on my Galaxy Note and Galaxy S4First one , my phone started saying it was removed , then recognize it again :) then diedI thought it's just a luck , plugged in the 2nd one :) stayed for about 2 months and died suddenly ! and lost everythingnever buying from SanDisk again .. ever",
  'review_es': 'Compré 2 de esas tarjetas microSD de SanDisk de 32 GB, las usé en mi Galaxy Note y Galaxy S4. La primera tarjeta, mi teléfono comenzó a decir que había sido retirada, luego la volvió a reconocer y murió. Pensé que era solo mala suerte, así que conecté la segunda tarjeta y duró unos 2 meses y murió de repente. Nunca más compraré de SanDisk... nunca',
  'categoria': 'Falla'},
 'review2': {'review_original': 'I bougth this micro SD card after some trubles with other that i got from Kingston, i can tell that SanDisk is other quality, this is the best, my i9300 phone can read a 64GB very fast, the dta transfer speed from my pc to my is amazing, if you are looking for additional storage to you phone, for music, pictures and other type of files, this is for you.',
  'review_es': 'Compré esta tarjeta microSD después de algunos problemas con otra que compré de Kingston, puedo decir que SanDisk es de otra calidad, esta es la mejor, mi teléfono i9300 puede leer un 64GB muy rápido, la velocidad de transferencia de datos desde mi pc hasta mi teléfono es impresionante, si buscas almacenamiento adicional para tu teléfono, para música, fotos y otros tipos de archivos, esta es para ti.',
  'categoria': 'Calidad'},
 'review3': {'review_original': "Ordered this for a Galaxy S3.  Lasted a few months and then broke.  Is not accessible on several different PC's.Says 'limited lifetime' warranty - BS.  You have ONE MONTH for Eco Zone.  Not only did I lose pictures but now I am out $$ because of a crappy return policy.",
  'review_es': "Pedí esto para un Galaxy S3. Duró unos meses y luego se rompió. No es accesible en varios PC diferentes. Dice 'garantía de por vida' - tonterías. Tienes UN MES para la zona Eco. No solo perdí fotos, sino que ahora estoy fuera de $$ debido a una política de devolución defectuosa.",
  'categoria': 'Garantia'},
 'review4': {'review_original': 'I used this for a few months in my phone, then it decided to quit mounting. I lost some pictures of pets who died shortly after. I got a replacement card, but I had to send in the old one, giving up any chance of recovering its contents.',
  'review_es': 'Usé esto durante unos meses en mi teléfono, luego decidió dejar de montar. Perdí algunas fotos de mascotas que murieron poco después. Obtuve una tarjeta de reemplazo, pero tuve que enviar la antigua, renunciando a cualquier posibilidad de recuperar su contenido.',
  'categoria': 'Pérdida'},
 'review5': {'review_original': "This card advertises itself as UHS1 but it's actually UHS50.This means that it will not go up to SDR104 speeds/throughput.Not necessary bad, just false advertising.",
  'review_es': 'Esta tarjeta se anuncia como UHS1 pero en realidad es UHS50. Esto significa que no alcanzará velocidades/rendimiento SDR104. No es necesariamente mala, solo publicidad falsa.',
  'categoria': 'Publicidad'}}

In [286]:
len(dic_reviews_negativas_clasificadas)

5

In [293]:
dic_reviews_negativas_clasificadas["review1"]

{'review_original': "I bought 2 of those SanDisk 32 GB microSD , used them on my Galaxy Note and Galaxy S4First one , my phone started saying it was removed , then recognize it again :) then diedI thought it's just a luck , plugged in the 2nd one :) stayed for about 2 months and died suddenly ! and lost everythingnever buying from SanDisk again .. ever",
 'review_es': 'Compré 2 de esas tarjetas microSD de SanDisk de 32 GB, las usé en mi Galaxy Note y Galaxy S4. La primera tarjeta, mi teléfono comenzó a decir que había sido retirada, luego la volvió a reconocer y murió. Pensé que era solo mala suerte, así que conecté la segunda tarjeta y duró unos 2 meses y murió de repente. Nunca más compraré de SanDisk... nunca',
 'categoria': 'Falla'}

# Desafío Final (usando un IDE)

**1.** Cargar un archivo `.txt`, donde cada línea será un elemento de una lista de Python.

**2.** Mandársela al modelo que estás corriendo localmente para extraer, en formato JSON, donde cada ítem tendrá:
- `usuario`
- `reseña original`
- `reseña_es`
- `evaluación` *(Positiva, Negativa, Neutra)*

**3.** Transformar la respuesta del modelo en una lista de diccionarios Python.

**4.** Crear una función que, dada una lista de diccionarios, recorra la lista y haga 2 cosas:

- **a)** Contar la cantidad de evaluaciones positivas, negativas y neutras.
- **b)** Unir cada ítem de esa lista en una variable de tipo `string` con algún separador.

> Al final, retornar ambas cosas.